E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/source/E4ISD2_rtos_hello.c File Reference
E4ISD2_rtos_hello.c File Reference
Application entry point.
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "timers.h"
#include "fsl_device_registers.h"
#include "fsl_debug_console.h"
#include "board.h"
#include "rgbLed.h"
Functions
static void SetupHardware (void)
static void vLEDTask1 (void *pvParameters)
static void vLEDTask2 (void *pvParameters)
int main (void)
main routine for FreeRTOS blinky example
Detailed Description
Application entry point.
Definition in file E4ISD2_rtos_hello.c.
Function Documentation
main()
int main (void)
main routine for FreeRTOS blinky example
Returns
Nothing, function should not exit
Definition at line 73 of file E4ISD2_rtos_hello.c.
References configMINIMAL_STACK_SIZE, PRINTF, SetupHardware(), tskIDLE_PRIORITY, vLEDTask1(), vLEDTask2(), and vTaskStartScheduler().
Referenced by __attribute__().
SetupHardware()
static void SetupHardware (void) static
Definition at line 29 of file E4ISD2_rtos_hello.c.
References BOARD_BootClockRUN(), BOARD_InitDebugConsole(), BOARD_InitPins(), and init_rgb().
Referenced by main().
vLEDTask1()
static void vLEDTask1 (void * pvParameters) static
Definition at line 40 of file E4ISD2_rtos_hello.c.
References BLUE, configTICK_RATE_HZ, set_rgb(), and vTaskDelay().
Referenced by main().
vLEDTask2()
static void vLEDTask2 (void * pvParameters) static
Definition at line 53 of file E4ISD2_rtos_hello.c.
References configTICK_RATE_HZ, GREEN, set_rgb(), and vTaskDelay().
Referenced by main().