E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/board/clock_config.c File Reference
clock_config.c File Reference
#include "fsl_smc.h"
#include "clock_config.h"
Macros
#define MCG_PLL_DISABLE 0U
#define OSC_CAP0P 0U
#define OSC_ER_CLK_DISABLE 0U
#define SIM_OSC32KSEL_LPO_CLK 3U
#define SIM_PLLFLLSEL_MCGFLLCLK_CLK 0U
#define SIM_PLLFLLSEL_MCGPLLCLK_CLK 1U
Functions
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
static void CLOCK_CONFIG_SetFllExtRefDiv (uint8_t frdiv)
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
void BOARD_BootClockVLPR (void)
This function executes configuration of clocks.
Variables
uint32_t SystemCoreClock
const mcg_config_t mcgConfig_BOARD_BootClockRUN
MCG set for BOARD_BootClockRUN configuration.
const sim_clock_config_t simConfig_BOARD_BootClockRUN
SIM module set for BOARD_BootClockRUN configuration.
const osc_config_t oscConfig_BOARD_BootClockRUN
OSC set for BOARD_BootClockRUN configuration.
const mcg_config_t mcgConfig_BOARD_BootClockVLPR
MCG set for BOARD_BootClockVLPR configuration.
const sim_clock_config_t simConfig_BOARD_BootClockVLPR
SIM module set for BOARD_BootClockVLPR configuration.
const osc_config_t oscConfig_BOARD_BootClockVLPR
OSC set for BOARD_BootClockVLPR configuration.
Macro Definition Documentation
MCG_PLL_DISABLE
#define MCG_PLL_DISABLE 0U
MCGPLLCLK disabled
Definition at line 75 of file clock_config.c.
OSC_CAP0P
#define OSC_CAP0P 0U
Oscillator 0pF capacitor load
Definition at line 76 of file clock_config.c.
OSC_ER_CLK_DISABLE
#define OSC_ER_CLK_DISABLE 0U
Disable external reference clock
Definition at line 77 of file clock_config.c.
SIM_OSC32KSEL_LPO_CLK
#define SIM_OSC32KSEL_LPO_CLK 3U
OSC32KSEL select: LPO clock
Definition at line 78 of file clock_config.c.
SIM_PLLFLLSEL_MCGFLLCLK_CLK
#define SIM_PLLFLLSEL_MCGFLLCLK_CLK 0U
PLLFLL select: MCGFLLCLK clock
Definition at line 79 of file clock_config.c.
SIM_PLLFLLSEL_MCGPLLCLK_CLK
#define SIM_PLLFLLSEL_MCGPLLCLK_CLK 1U
PLLFLL select: MCGPLLCLK clock
Definition at line 80 of file clock_config.c.
Function Documentation
BOARD_BootClockRUN()
void BOARD_BootClockRUN (void)
This function executes configuration of clocks.
Definition at line 192 of file clock_config.c.
References BOARD_BOOTCLOCKRUN_CORE_CLOCK, CLOCK_CONFIG_SetFllExtRefDiv(), mcgConfig_BOARD_BootClockRUN, oscConfig_BOARD_BootClockRUN, simConfig_BOARD_BootClockRUN, and SystemCoreClock.
Referenced by BOARD_InitBootClocks(), and SetupHardware().
BOARD_BootClockVLPR()
void BOARD_BootClockVLPR (void)
This function executes configuration of clocks.
Definition at line 285 of file clock_config.c.
References BOARD_BOOTCLOCKVLPR_CORE_CLOCK, mcgConfig_BOARD_BootClockVLPR, simConfig_BOARD_BootClockVLPR, and SystemCoreClock.
BOARD_InitBootClocks()
void BOARD_InitBootClocks (void)
This function executes default configuration of clocks.
Definition at line 95 of file clock_config.c.
References BOARD_BootClockRUN().
CLOCK_CONFIG_SetFllExtRefDiv()
static void CLOCK_CONFIG_SetFllExtRefDiv (uint8_t frdiv) static
Definition at line 107 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
Variable Documentation
mcgConfig_BOARD_BootClockRUN
const mcg_config_t mcgConfig_BOARD_BootClockRUN
Initial value:
=
    {
        .mcgMode = kMCG_ModePEE,
        .irclkEnableMode = kMCG_IrclkEnable,
        .ircs = kMCG_IrcSlow,
        .fcrdiv = 0x0U,
        .frdiv = 0x0U,
        .drs = kMCG_DrsLow,
        .dmx32 = kMCG_Dmx32Default,
        .pll0Config =
            {
                .enableMode = MCG_PLL_DISABLE,
                .prdiv = 0x1U,
                .vdiv = 0x0U,
            },
    }
MCG set for BOARD_BootClockRUN configuration.
Definition at line 156 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
mcgConfig_BOARD_BootClockVLPR
const mcg_config_t mcgConfig_BOARD_BootClockVLPR
Initial value:
=
    {
        .mcgMode = kMCG_ModeBLPI,
        .irclkEnableMode = kMCG_IrclkEnable,
        .ircs = kMCG_IrcFast,
        .fcrdiv = 0x0U,
        .frdiv = 0x0U,
        .drs = kMCG_DrsLow,
        .dmx32 = kMCG_Dmx32Default,
        .pll0Config =
            {
                .enableMode = MCG_PLL_DISABLE,
                .prdiv = 0x0U,
                .vdiv = 0x0U,
            },
    }
MCG set for BOARD_BootClockVLPR configuration.
Definition at line 249 of file clock_config.c.
Referenced by BOARD_BootClockVLPR().
oscConfig_BOARD_BootClockRUN
const osc_config_t oscConfig_BOARD_BootClockRUN
Initial value:
=
    {
        .freq = 8000000U,
        .capLoad = (OSC_CAP0P),
        .workMode = kOSC_ModeOscLowPower,
        .oscerConfig =
            {
                .enableMode = kOSC_ErClkEnable,
            }
    }
OSC set for BOARD_BootClockRUN configuration.
Definition at line 178 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
oscConfig_BOARD_BootClockVLPR
const osc_config_t oscConfig_BOARD_BootClockVLPR
Initial value:
=
    {
        .freq = 0U,
        .capLoad = (OSC_CAP0P),
        .workMode = kOSC_ModeOscLowPower,
        .oscerConfig =
            {
                .enableMode = OSC_ER_CLK_DISABLE,
            }
    }
OSC set for BOARD_BootClockVLPR configuration.
Definition at line 271 of file clock_config.c.
simConfig_BOARD_BootClockRUN
const sim_clock_config_t simConfig_BOARD_BootClockRUN
Initial value:
=
    {
        .pllFllSel = SIM_PLLFLLSEL_MCGPLLCLK_CLK,
        .er32kSrc = SIM_OSC32KSEL_LPO_CLK,
        .clkdiv1 = 0x10010000U,
    }
SIM module set for BOARD_BootClockRUN configuration.
Definition at line 172 of file clock_config.c.
Referenced by BOARD_BootClockRUN().
simConfig_BOARD_BootClockVLPR
const sim_clock_config_t simConfig_BOARD_BootClockVLPR
Initial value:
=
    {
        .pllFllSel = SIM_PLLFLLSEL_MCGFLLCLK_CLK,
        .er32kSrc = SIM_OSC32KSEL_LPO_CLK,
        .clkdiv1 = 0x40000U,
    }
SIM module set for BOARD_BootClockVLPR configuration.
Definition at line 265 of file clock_config.c.
Referenced by BOARD_BootClockVLPR().
SystemCoreClock
uint32_t SystemCoreClock
Referenced by BOARD_BootClockRUN(), and BOARD_BootClockVLPR().