E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/freertos/event_groups.h File Reference
event_groups.h File Reference
#include "timers.h"
Macros
#define xEventGroupClearBitsFromISR(xEventGroup, uxBitsToClear) xTimerPendFunctionCallFromISR(vEventGroupClearBitsCallback, (void *) xEventGroup, (uint32_t) uxBitsToClear, NULL)
#define xEventGroupSetBitsFromISR(xEventGroup, uxBitsToSet, pxHigherPriorityTaskWoken) xTimerPendFunctionCallFromISR(vEventGroupSetBitsCallback, (void *) xEventGroup, (uint32_t) uxBitsToSet, pxHigherPriorityTaskWoken)
#define xEventGroupGetBits(xEventGroup) xEventGroupClearBits(xEventGroup, 0)
Typedefs
typedef void * EventGroupHandle_t
typedef TickType_t EventBits_t
Functions
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear) PRIVILEGED_FUNCTION
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet) PRIVILEGED_FUNCTION
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup) PRIVILEGED_FUNCTION
void vEventGroupDelete (EventGroupHandle_t xEventGroup) PRIVILEGED_FUNCTION
void vEventGroupSetBitsCallback (void *pvEventGroup, const uint32_t ulBitsToSet) PRIVILEGED_FUNCTION
void vEventGroupClearBitsCallback (void *pvEventGroup, const uint32_t ulBitsToClear) PRIVILEGED_FUNCTION
Macro Definition Documentation
xEventGroupClearBitsFromISR
#define xEventGroupClearBitsFromISR (xEventGroup, uxBitsToClear) xTimerPendFunctionCallFromISR(vEventGroupClearBitsCallback, (void *) xEventGroup, (uint32_t) uxBitsToClear, NULL)
Definition at line 451 of file event_groups.h.
xEventGroupGetBits
#define xEventGroupGetBits (xEventGroup) xEventGroupClearBits(xEventGroup, 0)
Definition at line 749 of file event_groups.h.
xEventGroupSetBitsFromISR
#define xEventGroupSetBitsFromISR (xEventGroup, uxBitsToSet, pxHigherPriorityTaskWoken) xTimerPendFunctionCallFromISR(vEventGroupSetBitsCallback, (void *) xEventGroup, (uint32_t) uxBitsToSet, pxHigherPriorityTaskWoken)
Definition at line 603 of file event_groups.h.
Typedef Documentation
EventBits_t
typedef TickType_t EventBits_t
Definition at line 133 of file event_groups.h.
EventGroupHandle_t
typedef void* EventGroupHandle_t
Definition at line 123 of file event_groups.h.
Function Documentation
vEventGroupClearBitsCallback()
void vEventGroupClearBitsCallback (void * pvEventGroup, const uint32_t ulBitsToClear)
Definition at line 676 of file event_groups.c.
References xEventGroupClearBits().
Referenced by xEventGroupClearBitsFromISR().
vEventGroupDelete()
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
event_groups.h
   void xEventGroupDelete( EventGroupHandle_t xEventGroup );
Delete an event group that was previously created by a call to xEventGroupCreate(). Tasks that are blocked on the event group will be unblocked and obtain 0 as the event group's value.
Parameters
xEventGroup The event group being deleted.
Definition at line 624 of file event_groups.c.
References configASSERT, eventUNBLOCKED_DUE_TO_BIT_SET, listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, pdFALSE, xMINI_LIST_ITEM::pxNext, traceEVENT_GROUP_DELETE, vPortFree(), vTaskSuspendAll(), xLIST::xListEnd, xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
vEventGroupSetBitsCallback()
void vEventGroupSetBitsCallback (void * pvEventGroup, const uint32_t ulBitsToSet)
Definition at line 668 of file event_groups.c.
References xEventGroupSetBits().
Referenced by xEventGroupSetBitsFromISR().
xEventGroupClearBits()
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
Definition at line 472 of file event_groups.c.
References configASSERT, eventEVENT_BITS_CONTROL_BYTES, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceEVENT_GROUP_CLEAR_BITS, and xEventGroupDefinition::uxEventBits.
Referenced by vEventGroupClearBitsCallback().
xEventGroupGetBitsFromISR()
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
Definition at line 514 of file event_groups.c.
References portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xEventGroupDefinition::uxEventBits.
xEventGroupSetBits()
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
Definition at line 530 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, listGET_END_MARKER, listGET_HEAD_ENTRY, listGET_LIST_ITEM_VALUE, listGET_NEXT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, traceEVENT_GROUP_SET_BITS, xEventGroupDefinition::uxEventBits, vTaskSuspendAll(), xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
Referenced by vEventGroupSetBitsCallback(), and xEventGroupSync().
xEventGroupSync()
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
Definition at line 208 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_SYNC_BLOCK, traceEVENT_GROUP_SYNC_END, xEventGroupDefinition::uxEventBits, uxTaskResetEventItemValue(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xEventGroupSetBits(), xTaskGetSchedulerState(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
xEventGroupWaitBits()
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
Definition at line 324 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvTestWaitCondition(), taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_WAIT_BITS_BLOCK, traceEVENT_GROUP_WAIT_BITS_END, xEventGroupDefinition::uxEventBits, uxTaskResetEventItemValue(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xTaskGetSchedulerState(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.