E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/utilities/fsl_debug_console.c File Reference
fsl_debug_console.c File Reference
#include <stdarg.h>
#include <stdlib.h>
#include <math.h>
#include "fsl_debug_console.h"
Data Structures
struct DebugConsoleOperationFunctions
Operation functions definitions for debug console.
struct DebugConsoleState
State structure storing debug console.
Macros
#define IO_MAXLINE 20U
Keil: suppress ellipsis warning in va_arg usage below.
#define HUGE_VAL (99.e99)
The overflow value.
Typedefs
typedef struct DebugConsoleOperationFunctions debug_console_ops_t
Operation functions definitions for debug console.
typedef struct DebugConsoleState debug_console_state_t
State structure storing debug console.
typedef int(* PUTCHAR_FUNC) (int a)
Type of KSDK printf function pointer.
Enumerations
enum _debugconsole_scanf_flag {
kSCANF_Suppress = 0x2U, kSCANF_DestMask = 0x7cU, kSCANF_DestChar = 0x4U, kSCANF_DestString = 0x8U,
kSCANF_DestSet = 0x10U, kSCANF_DestInt = 0x20U, kSCANF_DestFloat = 0x30U, kSCANF_LengthMask = 0x1f00U,
kSCANF_TypeSinged = 0x2000U
}
Specification modifier flags for scanf.
Functions
static int DbgConsole_PrintfFormattedData (PUTCHAR_FUNC func_ptr, const char *fmt, va_list ap)
This function outputs its parameters according to a formatted string.
static int DbgConsole_ScanfFormattedData (const char *line_ptr, char *format, va_list args_ptr)
Converts an input line of ASCII characters based upon a provided string format.
double modf (double input_dbl, double *intpart_ptr)
status_t DbgConsole_Init (uint32_t baseAddr, uint32_t baudRate, uint8_t device, uint32_t clkSrcFreq)
Initializes the the peripheral used for debug messages.
status_t DbgConsole_Deinit (void)
De-initializes the peripheral used for debug messages.
int DbgConsole_Printf (const char *fmt_s,...)
Writes formatted output to the standard output stream.
int DbgConsole_Putchar (int ch)
Writes a character to stdout.
int DbgConsole_Scanf (char *fmt_ptr,...)
Reads formatted data from the standard input stream.
int DbgConsole_Getchar (void)
Reads a character from standard input.
static uint32_t DbgConsole_ScanIgnoreWhiteSpace (const char **s)
Scanline function which ignores white spaces.
static void DbgConsole_PrintfPaddingCharacter (char c, int32_t curlen, int32_t width, int32_t *count, PUTCHAR_FUNC func_ptr)
This function puts padding character.
static int32_t DbgConsole_ConvertRadixNumToString (char *numstr, void *nump, int32_t neg, int32_t radix, bool use_caps)
Converts a radix number to a string and return its length.
Variables
static debug_console_state_t s_debugConsole = {.type = DEBUG_CONSOLE_DEVICE_TYPE_NONE, .base = NULL, .ops = {{0}, {0}}}
Debug UART state information.
Macro Definition Documentation
HUGE_VAL
#define HUGE_VAL (99.e99)
The overflow value.
Definition at line 108 of file fsl_debug_console.c.
Referenced by DbgConsole_ScanfFormattedData().
IO_MAXLINE
#define IO_MAXLINE 20U
Keil: suppress ellipsis warning in va_arg usage below.
This definition is maximum line that debugconsole can scanf each time.
Definition at line 104 of file fsl_debug_console.c.
Referenced by DbgConsole_Scanf().
Typedef Documentation
debug_console_ops_t
typedef struct DebugConsoleOperationFunctions debug_console_ops_t
Operation functions definitions for debug console.
debug_console_state_t
typedef struct DebugConsoleState debug_console_state_t
State structure storing debug console.
PUTCHAR_FUNC
typedef int(* PUTCHAR_FUNC) (int a)
Type of KSDK printf function pointer.
Definition at line 169 of file fsl_debug_console.c.
Enumeration Type Documentation
_debugconsole_scanf_flag
enum _debugconsole_scanf_flag
Specification modifier flags for scanf.
Enumerator
kSCANF_Suppress
Suppress Flag.
kSCANF_DestMask
Destination Mask.
kSCANF_DestChar
Destination Char Flag.
kSCANF_DestString
Destination String FLag.
kSCANF_DestSet
Destination Set Flag.
kSCANF_DestInt
Destination Int Flag.
kSCANF_DestFloat
Destination Float Flag.
kSCANF_LengthMask
Length Mask Flag.
kSCANF_TypeSinged
TypeSinged Flag.
Definition at line 188 of file fsl_debug_console.c.
Function Documentation
DbgConsole_ConvertRadixNumToString()
static int32_t DbgConsole_ConvertRadixNumToString (char * numstr, void * nump, int32_t neg, int32_t radix, bool use_caps) static
Converts a radix number to a string and return its length.
Parameters
[in] numstr Converted string of the number.
[in] nump Pointer to the number.
[in] neg Polarity of the number.
[in] radix The radix to be converted to.
[in] use_caps Used to identify x/X output format.
Returns
Length of the converted string.
Definition at line 544 of file fsl_debug_console.c.
References modf().
Referenced by DbgConsole_PrintfFormattedData().
DbgConsole_Deinit()
status_t DbgConsole_Deinit (void)
De-initializes the peripheral used for debug messages.
Call this function to disable debug log messages to be output via the specified peripheral base address and at the specified baud rate.
Returns
Indicates whether de-initialization was successful or not.
Definition at line 334 of file fsl_debug_console.c.
References DebugConsoleState::base, and DebugConsoleState::type.
DbgConsole_Getchar()
int DbgConsole_Getchar (void)
Reads a character from standard input.
Call this function to read a character from standard input.
Returns
Returns the character read.
Definition at line 474 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleOperationFunctions::GetChar, DebugConsoleState::ops, DebugConsoleOperationFunctions::rx_union, and DebugConsoleState::type.
Referenced by DbgConsole_Scanf().
DbgConsole_Init()
status_t DbgConsole_Init (uint32_t baseAddr, uint32_t baudRate, uint8_t device, uint32_t clkSrcFreq)
Initializes the the peripheral used for debug messages.
Call this function to enable debug log messages to be output via the specified peripheral, frequency of peripheral source clock, and base address at the specified baud rate. After this function has returned, stdout and stdin are connected to the selected peripheral.
Parameters
baseAddr Indicates the address of the peripheral used to send debug messages.
baudRate The desired baud rate in bits per second.
device Low level device type for the debug console, can be one of the following.
DEBUG_CONSOLE_DEVICE_TYPE_UART,
DEBUG_CONSOLE_DEVICE_TYPE_LPUART,
DEBUG_CONSOLE_DEVICE_TYPE_LPSCI,
DEBUG_CONSOLE_DEVICE_TYPE_USBCDC.
clkSrcFreq Frequency of peripheral source clock.
Returns
Indicates whether initialization was successful or not.
Return values
kStatus_Success Execution successfully
kStatus_Fail Execution failure
kStatus_InvalidArgument Invalid argument existed
Definition at line 232 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleState::ops, DebugConsoleOperationFunctions::rx_union, DebugConsoleOperationFunctions::tx_union, and DebugConsoleState::type.
Referenced by BOARD_InitDebugConsole().
DbgConsole_Printf()
int DbgConsole_Printf (const char * fmt_s, ...)
Writes formatted output to the standard output stream.
Call this function to write a formatted output to the standard output stream.
Parameters
fmt_s Format control string.
Returns
Returns the number of characters printed or a negative value if an error occurs.
Definition at line 393 of file fsl_debug_console.c.
References DbgConsole_PrintfFormattedData(), DbgConsole_Putchar(), and DebugConsoleState::type.
DbgConsole_PrintfFormattedData()
static int DbgConsole_PrintfFormattedData (PUTCHAR_FUNC func_ptr, const char * fmt, va_list ap) static
This function outputs its parameters according to a formatted string.
Note
I/O is performed by calling given function pointer using following (*func_ptr)(c);
Parameters
[in] func_ptr Function to put character out.
[in] fmt_ptr Format string for printf.
[in] args_ptr Arguments to printf.
Returns
Number of characters
Definition at line 775 of file fsl_debug_console.c.
References DbgConsole_ConvertRadixNumToString(), and DbgConsole_PrintfPaddingCharacter().
Referenced by DbgConsole_Printf().
DbgConsole_PrintfPaddingCharacter()
static void DbgConsole_PrintfPaddingCharacter (char c, int32_t curlen, int32_t width, int32_t * count, PUTCHAR_FUNC func_ptr) static
This function puts padding character.
Parameters
[in] c Padding character.
[in] curlen Length of current formatted string .
[in] width Width of expected formatted string.
[in] count Number of characters.
[in] func_ptr Function to put character out.
Definition at line 521 of file fsl_debug_console.c.
Referenced by DbgConsole_PrintfFormattedData().
DbgConsole_Putchar()
int DbgConsole_Putchar (int ch)
Writes a character to stdout.
Call this function to write a character to stdout.
Parameters
ch Character to be written.
Returns
Returns the character written.
Definition at line 411 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleState::ops, DebugConsoleOperationFunctions::PutChar, DebugConsoleOperationFunctions::tx_union, and DebugConsoleState::type.
Referenced by DbgConsole_Printf().
DbgConsole_Scanf()
int DbgConsole_Scanf (char * fmt_ptr, ...)
Reads formatted data from the standard input stream.
Call this function to read formatted data from the standard input stream.
Parameters
fmt_ptr Format control string.
Returns
Returns the number of fields successfully converted and assigned.
Definition at line 424 of file fsl_debug_console.c.
References DbgConsole_Getchar(), DbgConsole_ScanfFormattedData(), IO_MAXLINE, and DebugConsoleState::type.
DbgConsole_ScanfFormattedData()
static int DbgConsole_ScanfFormattedData (const char * line_ptr, char * format, va_list args_ptr) static
Converts an input line of ASCII characters based upon a provided string format.
Parameters
[in] line_ptr The input line of ASCII data.
[in] format Format first points to the format string.
[in] args_ptr The list of parameters.
Returns
Number of input items converted and assigned.
Return values
IO_EOF When line_ptr is empty string "".
Definition at line 1316 of file fsl_debug_console.c.
References __attribute__(), DebugConsoleState::base, DbgConsole_ScanIgnoreWhiteSpace(), DebugConsoleOperationFunctions::GetChar, HUGE_VAL, kSCANF_DestChar, kSCANF_DestFloat, kSCANF_DestInt, kSCANF_DestMask, kSCANF_DestString, kSCANF_LengthMask, kSCANF_Suppress, kSCANF_TypeSinged, DebugConsoleState::ops, DebugConsoleOperationFunctions::PutChar, DebugConsoleOperationFunctions::rx_union, DebugConsoleOperationFunctions::tx_union, and DebugConsoleState::type.
Referenced by DbgConsole_Scanf().
DbgConsole_ScanIgnoreWhiteSpace()
static uint32_t DbgConsole_ScanIgnoreWhiteSpace (const char ** s) static
Scanline function which ignores white spaces.
Parameters
[in] s The address of the string pointer to update.
Returns
String without white spaces.
Definition at line 497 of file fsl_debug_console.c.
Referenced by DbgConsole_ScanfFormattedData().
modf()
double modf (double input_dbl, double * intpart_ptr)
Referenced by DbgConsole_ConvertRadixNumToString().
Variable Documentation
s_debugConsole
debug_console_state_t s_debugConsole = {.type = DEBUG_CONSOLE_DEVICE_TYPE_NONE, .base = NULL, .ops = {{0}, {0}}} static
Debug UART state information.
Definition at line 214 of file fsl_debug_console.c.