E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/utilities/fsl_debug_console.h File Reference
fsl_debug_console.h File Reference
#include "fsl_common.h"
Macros
#define SDK_DEBUGCONSOLE 1U
Definition to select sdk or toolchain printf, scanf.
#define PRINTF_FLOAT_ENABLE 0U
Definition to printf the float number.
#define SCANF_FLOAT_ENABLE 0U
Definition to scanf the float number.
#define PRINTF_ADVANCED_ENABLE 0U
Definition to support advanced format specifier for printf.
#define SCANF_ADVANCED_ENABLE 0U
Definition to support advanced format specifier for scanf.
#define PRINTF DbgConsole_Printf
#define SCANF DbgConsole_Scanf
#define PUTCHAR DbgConsole_Putchar
#define GETCHAR DbgConsole_Getchar
Functions
Initialization
status_t DbgConsole_Init (uint32_t baseAddr, uint32_t baudRate, uint8_t device, uint32_t clkSrcFreq)
Initializes the the peripheral used for debug messages.
status_t DbgConsole_Deinit (void)
De-initializes the peripheral used for debug messages.
int DbgConsole_Printf (const char *fmt_s,...)
Writes formatted output to the standard output stream.
int DbgConsole_Putchar (int ch)
Writes a character to stdout.
int DbgConsole_Scanf (char *fmt_ptr,...)
Reads formatted data from the standard input stream.
int DbgConsole_Getchar (void)
Reads a character from standard input.
Macro Definition Documentation
GETCHAR
#define GETCHAR DbgConsole_Getchar
Definition at line 91 of file fsl_debug_console.h.
PRINTF
#define PRINTF DbgConsole_Printf
Definition at line 88 of file fsl_debug_console.h.
Referenced by main().
PRINTF_ADVANCED_ENABLE
#define PRINTF_ADVANCED_ENABLE 0U
Definition to support advanced format specifier for printf.
Definition at line 79 of file fsl_debug_console.h.
PRINTF_FLOAT_ENABLE
#define PRINTF_FLOAT_ENABLE 0U
Definition to printf the float number.
Definition at line 69 of file fsl_debug_console.h.
PUTCHAR
#define PUTCHAR DbgConsole_Putchar
Definition at line 90 of file fsl_debug_console.h.
SCANF
#define SCANF DbgConsole_Scanf
Definition at line 89 of file fsl_debug_console.h.
SCANF_ADVANCED_ENABLE
#define SCANF_ADVANCED_ENABLE 0U
Definition to support advanced format specifier for scanf.
Definition at line 84 of file fsl_debug_console.h.
SCANF_FLOAT_ENABLE
#define SCANF_FLOAT_ENABLE 0U
Definition to scanf the float number.
Definition at line 74 of file fsl_debug_console.h.
SDK_DEBUGCONSOLE
#define SDK_DEBUGCONSOLE 1U
Definition to select sdk or toolchain printf, scanf.
Definition at line 60 of file fsl_debug_console.h.
Function Documentation
DbgConsole_Deinit()
status_t DbgConsole_Deinit (void)
De-initializes the peripheral used for debug messages.
Call this function to disable debug log messages to be output via the specified peripheral base address and at the specified baud rate.
Returns
Indicates whether de-initialization was successful or not.
Definition at line 334 of file fsl_debug_console.c.
References DebugConsoleState::base, and DebugConsoleState::type.
DbgConsole_Getchar()
int DbgConsole_Getchar (void)
Reads a character from standard input.
Call this function to read a character from standard input.
Returns
Returns the character read.
Definition at line 474 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleOperationFunctions::GetChar, DebugConsoleState::ops, DebugConsoleOperationFunctions::rx_union, and DebugConsoleState::type.
Referenced by DbgConsole_Scanf().
DbgConsole_Init()
status_t DbgConsole_Init (uint32_t baseAddr, uint32_t baudRate, uint8_t device, uint32_t clkSrcFreq)
Initializes the the peripheral used for debug messages.
Call this function to enable debug log messages to be output via the specified peripheral, frequency of peripheral source clock, and base address at the specified baud rate. After this function has returned, stdout and stdin are connected to the selected peripheral.
Parameters
baseAddr Indicates the address of the peripheral used to send debug messages.
baudRate The desired baud rate in bits per second.
device Low level device type for the debug console, can be one of the following.
DEBUG_CONSOLE_DEVICE_TYPE_UART,
DEBUG_CONSOLE_DEVICE_TYPE_LPUART,
DEBUG_CONSOLE_DEVICE_TYPE_LPSCI,
DEBUG_CONSOLE_DEVICE_TYPE_USBCDC.
clkSrcFreq Frequency of peripheral source clock.
Returns
Indicates whether initialization was successful or not.
Return values
kStatus_Success Execution successfully
kStatus_Fail Execution failure
kStatus_InvalidArgument Invalid argument existed
Definition at line 232 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleState::ops, DebugConsoleOperationFunctions::rx_union, DebugConsoleOperationFunctions::tx_union, and DebugConsoleState::type.
Referenced by BOARD_InitDebugConsole().
DbgConsole_Printf()
int DbgConsole_Printf (const char * fmt_s, ...)
Writes formatted output to the standard output stream.
Call this function to write a formatted output to the standard output stream.
Parameters
fmt_s Format control string.
Returns
Returns the number of characters printed or a negative value if an error occurs.
Definition at line 393 of file fsl_debug_console.c.
References DbgConsole_PrintfFormattedData(), DbgConsole_Putchar(), and DebugConsoleState::type.
DbgConsole_Putchar()
int DbgConsole_Putchar (int ch)
Writes a character to stdout.
Call this function to write a character to stdout.
Parameters
ch Character to be written.
Returns
Returns the character written.
Definition at line 411 of file fsl_debug_console.c.
References DebugConsoleState::base, DebugConsoleState::ops, DebugConsoleOperationFunctions::PutChar, DebugConsoleOperationFunctions::tx_union, and DebugConsoleState::type.
Referenced by DbgConsole_Printf().
DbgConsole_Scanf()
int DbgConsole_Scanf (char * fmt_ptr, ...)
Reads formatted data from the standard input stream.
Call this function to read formatted data from the standard input stream.
Parameters
fmt_ptr Format control string.
Returns
Returns the number of fields successfully converted and assigned.
Definition at line 424 of file fsl_debug_console.c.
References DbgConsole_Getchar(), DbgConsole_ScanfFormattedData(), IO_MAXLINE, and DebugConsoleState::type.