E4ISDrtosHello: Pin_mux
Pin_mux
Functions
void BOARD_InitPins (void)
Configures pin routing and optionally pin electrical features.
void BOARD_InitBootPins (void)
Calls initialization functions.
Detailed Description
Function Documentation
BOARD_InitBootPins()
void BOARD_InitBootPins (void)
Calls initialization functions.
Definition at line 67 of file pin_mux.c.
References BOARD_InitPins().
BOARD_InitPins()
void BOARD_InitPins (void)
Configures pin routing and optionally pin electrical features.
Definition at line 78 of file pin_mux.c.
References PIN1_IDX, PIN2_IDX, SOPT5_UART0RXSRC_UART_RX, and SOPT5_UART0TXSRC_UART_TX.
Referenced by BOARD_InitBootPins(), and SetupHardware().