E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/freertos/heap_2.c File Reference
heap_2.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Data Structures
struct A_BLOCK_LINK
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
#define heapMINIMUM_BLOCK_SIZE ((size_t) (heapSTRUCT_SIZE * 2))
#define prvInsertBlockIntoFreeList(pxBlockToInsert)
Typedefs
typedef struct A_BLOCK_LINK BlockLink_t
Functions
static void prvHeapInit (void)
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
size_t xPortGetFreeHeapSize (void)
void vPortInitialiseBlocks (void)
Variables
static uint8_t ucHeap [configTOTAL_HEAP_SIZE]
static const uint16_t heapSTRUCT_SIZE = ((sizeof (BlockLink_t) + (portBYTE_ALIGNMENT - 1)) & ~portBYTE_ALIGNMENT_MASK)
static BlockLink_t xStart
static BlockLink_t xEnd
static size_t xFreeBytesRemaining = configADJUSTED_HEAP_SIZE
Macro Definition Documentation
configADJUSTED_HEAP_SIZE
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
Definition at line 96 of file heap_2.c.
Referenced by prvHeapInit(), and pvPortMalloc().
heapMINIMUM_BLOCK_SIZE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (heapSTRUCT_SIZE * 2))
Definition at line 123 of file heap_2.c.
Referenced by pvPortMalloc().
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 84 of file heap_2.c.
prvInsertBlockIntoFreeList
#define prvInsertBlockIntoFreeList (pxBlockToInsert)
Value:
{                                                                                   \
BlockLink_t *pxIterator;                                                            \
size_t xBlockSize;                                                                  \
                                                                                    \
    xBlockSize = pxBlockToInsert->xBlockSize;                                       \
                                                                                    \
    /* Iterate through the list until a block is found that has a larger size */    \
    /* than the block we are inserting. */                                          \
    for( pxIterator = &xStart; pxIterator->pxNextFreeBlock->xBlockSize < xBlockSize; pxIterator = pxIterator->pxNextFreeBlock ) \
    {                                                                               \
        /* There is nothing to do here - just iterate to the correct position. */   \
    }                                                                               \
                                                                                    \
    /* Update the list to include the block being inserted in the correct */        \
    /* position. */                                                                 \
    pxBlockToInsert->pxNextFreeBlock = pxIterator->pxNextFreeBlock;                 \
    pxIterator->pxNextFreeBlock = pxBlockToInsert;                                  \
}
Definition at line 139 of file heap_2.c.
Referenced by pvPortMalloc(), and vPortFree().
Typedef Documentation
BlockLink_t
typedef struct A_BLOCK_LINK BlockLink_t
Function Documentation
prvHeapInit()
static void prvHeapInit (void) static
Definition at line 291 of file heap_2.c.
References configADJUSTED_HEAP_SIZE, portBYTE_ALIGNMENT, portBYTE_ALIGNMENT_MASK, portPOINTER_SIZE_TYPE, A_BLOCK_LINK::pxNextFreeBlock, ucHeap, A_BLOCK_LINK::xBlockSize, and xEnd.
Referenced by pvPortMalloc().
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
Definition at line 160 of file heap_2.c.
References configADJUSTED_HEAP_SIZE, heapMINIMUM_BLOCK_SIZE, heapSTRUCT_SIZE, pdFALSE, pdTRUE, portBYTE_ALIGNMENT, portBYTE_ALIGNMENT_MASK, prvHeapInit(), prvInsertBlockIntoFreeList, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, vTaskSuspendAll(), A_BLOCK_LINK::xBlockSize, xStart, and xTaskResumeAll().
vPortFree()
void vPortFree (void * pv)
Definition at line 252 of file heap_2.c.
References heapSTRUCT_SIZE, prvInsertBlockIntoFreeList, traceFREE, vTaskSuspendAll(), A_BLOCK_LINK::xBlockSize, and xTaskResumeAll().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 285 of file heap_2.c.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 279 of file heap_2.c.
References xFreeBytesRemaining.
Variable Documentation
heapSTRUCT_SIZE
const uint16_t heapSTRUCT_SIZE = ((sizeof (BlockLink_t) + (portBYTE_ALIGNMENT - 1)) & ~portBYTE_ALIGNMENT_MASK) static
Definition at line 122 of file heap_2.c.
Referenced by pvPortMalloc(), and vPortFree().
ucHeap
uint8_t ucHeap[configTOTAL_HEAP_SIZE] static
Definition at line 109 of file heap_2.c.
Referenced by prvHeapInit().
xEnd
BlockLink_t xEnd static
Definition at line 126 of file heap_2.c.
Referenced by prvHeapInit().
xFreeBytesRemaining
size_t xFreeBytesRemaining = configADJUSTED_HEAP_SIZE static
Definition at line 130 of file heap_2.c.
Referenced by xPortGetFreeHeapSize().
xStart
BlockLink_t xStart static
Definition at line 126 of file heap_2.c.
Referenced by pvPortMalloc().