E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/freertos/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "fsl_tickless_generic.h"
Macros
#define portINITIAL_XPSR (0x01000000)
#define configKERNEL_INTERRUPT_PRIORITY 0
#define portTASK_RETURN_ADDRESS prvTaskExitError
Functions
void xPortPendSVHandler (void xPortSysTickHandler void)
static void prvTaskExitError (void)
void vPortSVCHandler (void)
void vPortStartFirstTask (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
uint32_t ulSetInterruptMaskFromISR (void)
void vClearInterruptMaskFromISR (uint32_t ulMask)
void xPortPendSVHandler (void)
void xPortSysTickHandler (void)
Variables
uint32_t SystemCoreClock
static UBaseType_t uxCriticalNesting = 0xaaaaaaaa
Macro Definition Documentation
configKERNEL_INTERRUPT_PRIORITY
#define configKERNEL_INTERRUPT_PRIORITY 0
Definition at line 88 of file port.c.
portINITIAL_XPSR
#define portINITIAL_XPSR (0x01000000)
Definition at line 82 of file port.c.
portTASK_RETURN_ADDRESS
#define portTASK_RETURN_ADDRESS prvTaskExitError
Definition at line 97 of file port.c.
Function Documentation
prvTaskExitError()
static void prvTaskExitError (void) static
Definition at line 143 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and uxCriticalNesting.
Referenced by xPortStartScheduler().
ulSetInterruptMaskFromISR()
uint32_t ulSetInterruptMaskFromISR (void)
Definition at line 261 of file port.c.
vClearInterruptMaskFromISR()
void vClearInterruptMaskFromISR (uint32_t ulMask)
Definition at line 274 of file port.c.
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 221 of file port.c.
References configASSERT, and uxCriticalNesting.
Referenced by vTaskEndScheduler().
vPortEnterCritical()
void vPortEnterCritical (void)
Definition at line 241 of file port.c.
References portDISABLE_INTERRUPTS, and uxCriticalNesting.
vPortExitCritical()
void vPortExitCritical (void)
Definition at line 250 of file port.c.
References configASSERT, portENABLE_INTERRUPTS, and uxCriticalNesting.
vPortStartFirstTask()
void vPortStartFirstTask (void)
Definition at line 164 of file port.c.
Referenced by xPortStartScheduler().
vPortSVCHandler()
void vPortSVCHandler (void)
Definition at line 157 of file port.c.
vPortYield()
void vPortYield (void)
Definition at line 229 of file port.c.
References portNVIC_INT_CTRL, and portNVIC_PENDSVSET.
xPortPendSVHandler() [1/2]
void xPortPendSVHandler (void xPortSysTickHandler void)
Definition at line 106 of file port.c.
xPortPendSVHandler() [2/2]
void xPortPendSVHandler (void)
Definition at line 286 of file port.c.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 194 of file port.c.
References portNVIC_PENDSV_PRI, portNVIC_SYSPRI2, portNVIC_SYSTICK_PRI, prvSetupTimerInterrupt(), prvTaskExitError(), uxCriticalNesting, and vPortStartFirstTask().
Referenced by vTaskStartScheduler().
xPortSysTickHandler()
void xPortSysTickHandler (void)
Definition at line 334 of file port.c.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portNVIC_INT_CTRL, portNVIC_PENDSVSET, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskIncrementTick().
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock
uxCriticalNesting
UBaseType_t uxCriticalNesting = 0xaaaaaaaa static
Definition at line 101 of file port.c.
Referenced by prvTaskExitError(), vPortEndScheduler(), vPortEnterCritical(), vPortExitCritical(), and xPortStartScheduler().