E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/source/rgbLed.c File Reference
rgbLed.c File Reference
#include "pin_mux.h"
#include "clock_config.h"
#include "rgbLed.h"
Macros
#define MASK(x) (1 << (x))
Functions
void init_rgb (void)
void set_rgb (rgb_color_t col)
Macro Definition Documentation
MASK
#define MASK (x) (1 << (x))
Definition at line 11 of file rgbLed.c.
Referenced by init_rgb().
Function Documentation
init_rgb()
void init_rgb (void)
Definition at line 13 of file rgbLed.c.
References BLUE_LED_SHIFT, GREEN_LED_SHIFT, MASK, and RED_LED_SHIFT.
Referenced by SetupHardware().
set_rgb()
void set_rgb (rgb_color_t col)
Definition at line 32 of file rgbLed.c.
References BLACK, BLUE, BLUE_OFF, BLUE_ON, CYAN, GREEN, GREEN_OFF, GREEN_ON, MAGENTA, RED, RED_OFF, RED_ON, WHITE, and YELLOW.
Referenced by vLEDTask1(), and vLEDTask2().