E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/startup/startup_mkl25z4.c File Reference
startup_mkl25z4.c File Reference
Macros
#define WEAK __attribute__ ((weak))
#define WEAK_AV __attribute__ ((weak, section(".after_vectors")))
#define ALIAS(f) __attribute__ ((weak, alias (#f)))
Functions
__attribute__ ((used, section(".FlashConfig"))) const
void ResetISR (void)
WEAK void NMI_Handler (void)
WEAK void HardFault_Handler (void)
WEAK void SVC_Handler (void)
WEAK void PendSV_Handler (void)
WEAK void SysTick_Handler (void)
WEAK void IntDefaultHandler (void)
WEAK void DMA0_IRQHandler (void)
WEAK void DMA1_IRQHandler (void)
WEAK void DMA2_IRQHandler (void)
WEAK void DMA3_IRQHandler (void)
WEAK void Reserved20_IRQHandler (void)
WEAK void FTFA_IRQHandler (void)
WEAK void LVD_LVW_IRQHandler (void)
WEAK void LLWU_IRQHandler (void)
WEAK void I2C0_IRQHandler (void)
WEAK void I2C1_IRQHandler (void)
WEAK void SPI0_IRQHandler (void)
WEAK void SPI1_IRQHandler (void)
WEAK void UART0_IRQHandler (void)
WEAK void UART1_IRQHandler (void)
WEAK void UART2_IRQHandler (void)
WEAK void ADC0_IRQHandler (void)
WEAK void CMP0_IRQHandler (void)
WEAK void TPM0_IRQHandler (void)
WEAK void TPM1_IRQHandler (void)
WEAK void TPM2_IRQHandler (void)
WEAK void RTC_IRQHandler (void)
WEAK void RTC_Seconds_IRQHandler (void)
WEAK void PIT_IRQHandler (void)
WEAK void Reserved39_IRQHandler (void)
WEAK void USB0_IRQHandler (void)
WEAK void DAC0_IRQHandler (void)
WEAK void TSI0_IRQHandler (void)
WEAK void MCG_IRQHandler (void)
WEAK void LPTMR0_IRQHandler (void)
WEAK void Reserved45_IRQHandler (void)
WEAK void PORTA_IRQHandler (void)
WEAK void PORTD_IRQHandler (void)
void DMA0_DriverIRQHandler (void DMA1_DriverIRQHandler() ALIAS(IntDefaultHandler) void)
__attribute__ ((section(".after_vectors.init_data")))
__attribute__ ((section(".after_vectors.init_bss")))
__attribute__ ((section(".after_vectors.reset")))
Variables
Flash_Config = {0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFE}
unsigned int __data_section_table
unsigned int __data_section_table_end
unsigned int __bss_section_table
unsigned int __bss_section_table_end
Macro Definition Documentation
ALIAS
#define ALIAS (f) __attribute__ ((weak, alias (#f)))
Definition at line 58 of file startup_mkl25z4.c.
WEAK
#define WEAK __attribute__ ((weak))
Definition at line 56 of file startup_mkl25z4.c.
WEAK_AV
#define WEAK_AV __attribute__ ((weak, section(".after_vectors")))
Definition at line 57 of file startup_mkl25z4.c.
Function Documentation
__attribute__() [1/4]
__attribute__ ((used, section(".FlashConfig"))) const
Definition at line 72 of file startup_mkl25z4.c.
__attribute__() [2/4]
__attribute__ ((section(".after_vectors.init_data")))
Definition at line 264 of file startup_mkl25z4.c.
__attribute__() [3/4]
__attribute__ ((section(".after_vectors.init_bss")))
Definition at line 273 of file startup_mkl25z4.c.
References __bss_section_table, __bss_section_table_end, __data_section_table, and __data_section_table_end.
__attribute__() [4/4]
__attribute__ ((section(".after_vectors.reset")))
Definition at line 298 of file startup_mkl25z4.c.
References __data_section_table, and main().
ADC0_IRQHandler()
WEAK_AV void ADC0_IRQHandler (void)
Definition at line 475 of file startup_mkl25z4.c.
CMP0_IRQHandler()
WEAK_AV void CMP0_IRQHandler (void)
Definition at line 479 of file startup_mkl25z4.c.
DAC0_IRQHandler()
WEAK_AV void DAC0_IRQHandler (void)
Definition at line 515 of file startup_mkl25z4.c.
DMA0_DriverIRQHandler()
void DMA0_DriverIRQHandler (void DMA1_DriverIRQHandler() ALIAS(IntDefaultHandler) void)
Definition at line 143 of file startup_mkl25z4.c.
Referenced by DMA0_IRQHandler().
DMA0_IRQHandler()
WEAK_AV void DMA0_IRQHandler (void)
Definition at line 415 of file startup_mkl25z4.c.
References DMA0_DriverIRQHandler().
DMA1_IRQHandler()
WEAK_AV void DMA1_IRQHandler (void)
Definition at line 419 of file startup_mkl25z4.c.
DMA2_IRQHandler()
WEAK_AV void DMA2_IRQHandler (void)
Definition at line 423 of file startup_mkl25z4.c.
DMA3_IRQHandler()
WEAK_AV void DMA3_IRQHandler (void)
Definition at line 427 of file startup_mkl25z4.c.
FTFA_IRQHandler()
WEAK_AV void FTFA_IRQHandler (void)
Definition at line 435 of file startup_mkl25z4.c.
HardFault_Handler()
WEAK_AV void HardFault_Handler (void)
Definition at line 385 of file startup_mkl25z4.c.
I2C0_IRQHandler()
WEAK_AV void I2C0_IRQHandler (void)
Definition at line 447 of file startup_mkl25z4.c.
I2C1_IRQHandler()
WEAK_AV void I2C1_IRQHandler (void)
Definition at line 451 of file startup_mkl25z4.c.
IntDefaultHandler()
WEAK_AV void IntDefaultHandler (void)
Definition at line 405 of file startup_mkl25z4.c.
LLWU_IRQHandler()
WEAK_AV void LLWU_IRQHandler (void)
Definition at line 443 of file startup_mkl25z4.c.
LPTMR0_IRQHandler()
WEAK_AV void LPTMR0_IRQHandler (void)
Definition at line 527 of file startup_mkl25z4.c.
LVD_LVW_IRQHandler()
WEAK_AV void LVD_LVW_IRQHandler (void)
Definition at line 439 of file startup_mkl25z4.c.
MCG_IRQHandler()
WEAK_AV void MCG_IRQHandler (void)
Definition at line 523 of file startup_mkl25z4.c.
NMI_Handler()
WEAK_AV void NMI_Handler (void)
Definition at line 381 of file startup_mkl25z4.c.
PendSV_Handler()
WEAK_AV void PendSV_Handler (void)
Definition at line 393 of file startup_mkl25z4.c.
PIT_IRQHandler()
WEAK_AV void PIT_IRQHandler (void)
Definition at line 503 of file startup_mkl25z4.c.
PORTA_IRQHandler()
WEAK_AV void PORTA_IRQHandler (void)
Definition at line 535 of file startup_mkl25z4.c.
PORTD_IRQHandler()
WEAK_AV void PORTD_IRQHandler (void)
Definition at line 539 of file startup_mkl25z4.c.
Reserved20_IRQHandler()
WEAK_AV void Reserved20_IRQHandler (void)
Definition at line 431 of file startup_mkl25z4.c.
Reserved39_IRQHandler()
WEAK_AV void Reserved39_IRQHandler (void)
Definition at line 507 of file startup_mkl25z4.c.
Reserved45_IRQHandler()
WEAK_AV void Reserved45_IRQHandler (void)
Definition at line 531 of file startup_mkl25z4.c.
ResetISR()
void ResetISR (void)
RTC_IRQHandler()
WEAK_AV void RTC_IRQHandler (void)
Definition at line 495 of file startup_mkl25z4.c.
RTC_Seconds_IRQHandler()
WEAK_AV void RTC_Seconds_IRQHandler (void)
Definition at line 499 of file startup_mkl25z4.c.
SPI0_IRQHandler()
WEAK_AV void SPI0_IRQHandler (void)
Definition at line 455 of file startup_mkl25z4.c.
SPI1_IRQHandler()
WEAK_AV void SPI1_IRQHandler (void)
Definition at line 459 of file startup_mkl25z4.c.
SVC_Handler()
WEAK_AV void SVC_Handler (void)
Definition at line 389 of file startup_mkl25z4.c.
SysTick_Handler()
WEAK_AV void SysTick_Handler (void)
Definition at line 397 of file startup_mkl25z4.c.
TPM0_IRQHandler()
WEAK_AV void TPM0_IRQHandler (void)
Definition at line 483 of file startup_mkl25z4.c.
TPM1_IRQHandler()
WEAK_AV void TPM1_IRQHandler (void)
Definition at line 487 of file startup_mkl25z4.c.
TPM2_IRQHandler()
WEAK_AV void TPM2_IRQHandler (void)
Definition at line 491 of file startup_mkl25z4.c.
TSI0_IRQHandler()
WEAK_AV void TSI0_IRQHandler (void)
Definition at line 519 of file startup_mkl25z4.c.
UART0_IRQHandler()
WEAK_AV void UART0_IRQHandler (void)
Definition at line 463 of file startup_mkl25z4.c.
UART1_IRQHandler()
WEAK_AV void UART1_IRQHandler (void)
Definition at line 467 of file startup_mkl25z4.c.
UART2_IRQHandler()
WEAK_AV void UART2_IRQHandler (void)
Definition at line 471 of file startup_mkl25z4.c.
USB0_IRQHandler()
WEAK_AV void USB0_IRQHandler (void)
Definition at line 511 of file startup_mkl25z4.c.
Variable Documentation
__bss_section_table
unsigned int __bss_section_table
Referenced by __attribute__().
__bss_section_table_end
unsigned int __bss_section_table_end
Referenced by __attribute__().
__data_section_table
unsigned int __data_section_table
Referenced by __attribute__().
__data_section_table_end
unsigned int __data_section_table_end
Referenced by __attribute__().
Flash_Config
Flash_Config = {0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFE}
Definition at line 77 of file startup_mkl25z4.c.