E4ISDrtosHello: DebugConsoleOperationFunctions Struct Reference
DebugConsoleOperationFunctions Struct Reference
Operation functions definitions for debug console.
Data Fields
union {
void(* PutChar)(void *base, const uint8_t
*buffer, size_t length)
} tx_union
union {
status_t(* GetChar)(void *base, const uint8_t
*buffer, size_t length)
} rx_union
Detailed Description
Operation functions definitions for debug console.
Definition at line 116 of file fsl_debug_console.c.
Field Documentation
GetChar
status_t(* DebugConsoleOperationFunctions::GetChar) (void *base, const uint8_t *buffer, size_t length)
Definition at line 140 of file fsl_debug_console.c.
Referenced by DbgConsole_Getchar(), and DbgConsole_ScanfFormattedData().
PutChar
void(* DebugConsoleOperationFunctions::PutChar) (void *base, const uint8_t *buffer, size_t length)
Definition at line 120 of file fsl_debug_console.c.
Referenced by DbgConsole_Putchar(), and DbgConsole_ScanfFormattedData().
rx_union
union { ... } DebugConsoleOperationFunctions::rx_union
Referenced by DbgConsole_Getchar(), DbgConsole_Init(), and DbgConsole_ScanfFormattedData().
tx_union
union { ... } DebugConsoleOperationFunctions::tx_union
Referenced by DbgConsole_Init(), DbgConsole_Putchar(), and DbgConsole_ScanfFormattedData().
The documentation for this struct was generated from the following file:
/Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/utilities/fsl_debug_console.c