E4ISDrtosHello: /Users/au263437/HIH/E4ISD2/workspace/E4ISD2_rtos_hello/freertos/tasks.c File Reference
tasks.c File Reference
#include <stdlib.h>
#include <string.h>
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "StackMacros.h"
Data Structures
struct tskTaskControlBlock
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define taskYIELD_IF_USING_PREEMPTION() portYIELD_WITHIN_API()
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
#define tskSTACK_FILL_BYTE (0xa5U)
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE (((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1)) || (portUSING_MPU_WRAPPERS == 1))
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
#define tskBLOCKED_CHAR ('B')
#define tskREADY_CHAR ('R')
#define tskDELETED_CHAR ('D')
#define tskSUSPENDED_CHAR ('S')
#define taskRECORD_READY_PRIORITY(uxPriority)
#define taskSELECT_HIGHEST_PRIORITY_TASK()
#define taskRESET_READY_PRIORITY(uxPriority)
#define portRESET_READY_PRIORITY(uxPriority, uxTopReadyPriority)
#define taskSWITCH_DELAYED_LISTS()
#define prvAddTaskToReadyList(pxTCB)
#define prvGetTCBFromHandle(pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Typedefs
typedef struct tskTaskControlBlock tskTCB
typedef tskTCB TCB_t
Functions
static BaseType_t prvTaskIsTaskSuspended (const TaskHandle_t xTask) PRIVILEGED_FUNCTION
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void)
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t *pxNewTCB, const MemoryRegion_t *const xRegions)
static void prvAddNewTaskToReadyList (TCB_t *pxNewTCB)
void vTaskDelete (TaskHandle_t xTaskToDelete)
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement)
void vTaskDelay (const TickType_t xTicksToDelay)
eTaskState eTaskGetState (TaskHandle_t xTask)
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask)
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask)
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority)
void vTaskSuspend (TaskHandle_t xTaskToSuspend)
void vTaskResume (TaskHandle_t xTaskToResume)
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume)
void vTaskStartScheduler (void)
void vTaskEndScheduler (void)
void vTaskSuspendAll (void)
BaseType_t xTaskResumeAll (void)
TickType_t xTaskGetTickCount (void)
TickType_t xTaskGetTickCountFromISR (void)
UBaseType_t uxTaskGetNumberOfTasks (void)
char * pcTaskGetName (TaskHandle_t xTaskToQuery)
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime)
BaseType_t xTaskIncrementTick (void)
void vTaskSwitchContext (void)
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
void vTaskPlaceOnUnorderedEventList (List_t *pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
BaseType_t xTaskRemoveFromUnorderedEventList (ListItem_t *pxEventListItem, const TickType_t xItemValue)
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
void vTaskMissedYield (void)
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask)
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle)
static portTASK_FUNCTION (prvIdleTask, pvParameters)
void vTaskSetThreadLocalStoragePointer (TaskHandle_t xTaskToSet, BaseType_t xIndex, void *pvValue)
void * pvTaskGetThreadLocalStoragePointer (TaskHandle_t xTaskToQuery, BaseType_t xIndex)
static void prvInitialiseTaskLists (void)
static void prvCheckTasksWaitingTermination (void)
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t *pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState)
static UBaseType_t prvListTasksWithinSingleList (TaskStatus_t *pxTaskStatusArray, List_t *pxList, eTaskState eState)
static uint16_t prvTaskCheckFreeStackSpace (const uint8_t *pucStackByte)
static void prvDeleteTCB (TCB_t *pxTCB)
static void prvResetNextTaskUnblockTime (void)
TaskHandle_t xTaskGetCurrentTaskHandle (void)
BaseType_t xTaskGetSchedulerState (void)
void vTaskPriorityInherit (TaskHandle_t const pxMutexHolder)
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder)
TickType_t uxTaskResetEventItemValue (void)
void * pvTaskIncrementMutexHeldCount (void)
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t *pulNotificationValue, TickType_t xTicksToWait)
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue)
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t *pulPreviousNotificationValue, BaseType_t *pxHigherPriorityTaskWoken)
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t *pxHigherPriorityTaskWoken)
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely)
Variables
PRIVILEGED_DATA TCB_t *volatile pxCurrentTCB = NULL
static PRIVILEGED_DATA List_t pxReadyTasksLists [configMAX_PRIORITIES]
static PRIVILEGED_DATA List_t xDelayedTaskList1
static PRIVILEGED_DATA List_t xDelayedTaskList2
static PRIVILEGED_DATA List_t *volatile pxDelayedTaskList
static PRIVILEGED_DATA List_t *volatile pxOverflowDelayedTaskList
static PRIVILEGED_DATA List_t xPendingReadyList
static PRIVILEGED_DATA List_t xTasksWaitingTermination
static PRIVILEGED_DATA volatile UBaseType_t uxDeletedTasksWaitingCleanUp = (UBaseType_t) 0U
static PRIVILEGED_DATA List_t xSuspendedTaskList
static PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) 0U
static PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY
static PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE
static PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE
static PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0
static PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U
static PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U
static PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL
static PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 77 of file tasks.c.
portRESET_READY_PRIORITY
#define portRESET_READY_PRIORITY (uxPriority, uxTopReadyPriority)
Definition at line 197 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), and vTaskPrioritySet().
prvAddTaskToReadyList
#define prvAddTaskToReadyList (pxTCB)
Value:
traceMOVED_TASK_TO_READY_STATE(pxTCB);                                                        \
    taskRECORD_READY_PRIORITY( ( pxTCB )->uxPriority );                                             \
    vListInsertEnd( &( pxReadyTasksLists[ ( pxTCB )->uxPriority ] ), &( ( pxTCB )->xStateListItem ) ); \
    tracePOST_MOVED_TASK_TO_READY_STATE( pxTCB )
Definition at line 259 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), uxTaskGetSystemState(), vTaskNotifyGiveFromISR(), vTaskPriorityInherit(), vTaskPrioritySet(), vTaskResume(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskPriorityDisinherit(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
prvGetTCBFromHandle
#define prvGetTCBFromHandle (pxHandle) (((pxHandle) == NULL) ? (TCB_t *) pxCurrentTCB : (TCB_t *) (pxHandle))
Definition at line 272 of file tasks.c.
Referenced by pcTaskGetName(), prvTaskCheckFreeStackSpace(), pvTaskGetThreadLocalStoragePointer(), uxTaskPriorityGet(), uxTaskPriorityGetFromISR(), vTaskDelete(), vTaskGetInfo(), vTaskPrioritySet(), vTaskSetThreadLocalStoragePointer(), vTaskSuspend(), and xTaskNotifyStateClear().
taskEVENT_LIST_ITEM_VALUE_IN_USE
#define taskEVENT_LIST_ITEM_VALUE_IN_USE 0x80000000UL
Definition at line 285 of file tasks.c.
Referenced by vTaskPlaceOnUnorderedEventList(), vTaskPriorityInherit(), vTaskPrioritySet(), and xTaskRemoveFromUnorderedEventList().
taskNOT_WAITING_NOTIFICATION
#define taskNOT_WAITING_NOTIFICATION ((uint8_t) 0)
Definition at line 110 of file tasks.c.
Referenced by prvInitialiseNewTask(), ulTaskNotifyTake(), xTaskNotifyStateClear(), and xTaskNotifyWait().
taskNOTIFICATION_RECEIVED
#define taskNOTIFICATION_RECEIVED ((uint8_t) 2)
Definition at line 112 of file tasks.c.
Referenced by vTaskNotifyGiveFromISR(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), xTaskNotifyStateClear(), and xTaskNotifyWait().
taskRECORD_READY_PRIORITY
#define taskRECORD_READY_PRIORITY (uxPriority)
Value:
{                                                                                                   \
        if( ( uxPriority ) > uxTopReadyPriority )                                                       \
        {                                                                                               \
            uxTopReadyPriority = ( uxPriority );                                                        \
        }                                                                                               \
    } /* taskRECORD_READY_PRIORITY */
Definition at line 164 of file tasks.c.
taskRESET_READY_PRIORITY
#define taskRESET_READY_PRIORITY (uxPriority)
Definition at line 196 of file tasks.c.
Referenced by vTaskDelete(), vTaskPriorityInherit(), vTaskSuspend(), and xTaskPriorityDisinherit().
taskSELECT_HIGHEST_PRIORITY_TASK
#define taskSELECT_HIGHEST_PRIORITY_TASK ()
Value:
{                                                                                                   \
    UBaseType_t uxTopPriority = uxTopReadyPriority;                                                     \
                                                                                                        \
        /* Find the highest priority queue that contains ready tasks. */                                \
        while( listLIST_IS_EMPTY( &( pxReadyTasksLists[ uxTopPriority ] ) ) )                           \
        {                                                                                               \
            configASSERT( uxTopPriority );                                                              \
            --uxTopPriority;                                                                            \
        }                                                                                               \
                                                                                                        \
        /* listGET_OWNER_OF_NEXT_ENTRY indexes through the list, so the tasks of                        \
        the same priority get an equal share of the processor time. */                                  \
        listGET_OWNER_OF_NEXT_ENTRY( pxCurrentTCB, &( pxReadyTasksLists[ uxTopPriority ] ) );           \
        uxTopReadyPriority = uxTopPriority;                                                             \
    } /* taskSELECT_HIGHEST_PRIORITY_TASK */
Definition at line 174 of file tasks.c.
Referenced by vTaskSwitchContext().
taskSWITCH_DELAYED_LISTS
#define taskSWITCH_DELAYED_LISTS ()
Value:
{                                                                                                   \
    List_t *pxTemp;                                                                                 \
                                                                                                    \
    /* The delayed tasks list should be empty when the lists are switched. */                       \
    configASSERT( ( listLIST_IS_EMPTY( pxDelayedTaskList ) ) );                                     \
                                                                                                    \
    pxTemp = pxDelayedTaskList;                                                                     \
    pxDelayedTaskList = pxOverflowDelayedTaskList;                                                  \
    pxOverflowDelayedTaskList = pxTemp;                                                             \
    xNumOfOverflows++;                                                                              \
    prvResetNextTaskUnblockTime();                                                                  \
}
Definition at line 239 of file tasks.c.
Referenced by xTaskIncrementTick().
taskWAITING_NOTIFICATION
#define taskWAITING_NOTIFICATION ((uint8_t) 1)
Definition at line 111 of file tasks.c.
Referenced by ulTaskNotifyTake(), vTaskNotifyGiveFromISR(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), and xTaskNotifyWait().
taskYIELD_IF_USING_PREEMPTION
#define taskYIELD_IF_USING_PREEMPTION () portYIELD_WITHIN_API()
Definition at line 106 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), vTaskPrioritySet(), vTaskResume(), xTaskGenericNotify(), and xTaskResumeAll().
tskBLOCKED_CHAR
#define tskBLOCKED_CHAR ('B')
Definition at line 143 of file tasks.c.
Referenced by xTaskPriorityDisinherit().
tskDELETED_CHAR
#define tskDELETED_CHAR ('D')
Definition at line 145 of file tasks.c.
Referenced by xTaskPriorityDisinherit().
tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB
#define tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 0)
Definition at line 136 of file tasks.c.
Referenced by prvDeleteTCB().
tskREADY_CHAR
#define tskREADY_CHAR ('R')
Definition at line 144 of file tasks.c.
Referenced by xTaskPriorityDisinherit().
tskSTACK_FILL_BYTE
#define tskSTACK_FILL_BYTE (0xa5U)
Definition at line 118 of file tasks.c.
Referenced by prvInitialiseNewTask(), and prvTaskCheckFreeStackSpace().
tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE
#define tskSTATIC_AND_DYNAMIC_ALLOCATION_POSSIBLE (((configSUPPORT_STATIC_ALLOCATION == 1) && (configSUPPORT_DYNAMIC_ALLOCATION == 1)) || (portUSING_MPU_WRAPPERS == 1))
Definition at line 135 of file tasks.c.
tskSTATICALLY_ALLOCATED_STACK_AND_TCB
#define tskSTATICALLY_ALLOCATED_STACK_AND_TCB ((uint8_t) 2)
Definition at line 138 of file tasks.c.
Referenced by prvDeleteTCB().
tskSTATICALLY_ALLOCATED_STACK_ONLY
#define tskSTATICALLY_ALLOCATED_STACK_ONLY ((uint8_t) 1)
Definition at line 137 of file tasks.c.
Referenced by prvDeleteTCB().
tskSUSPENDED_CHAR
#define tskSUSPENDED_CHAR ('S')
Definition at line 146 of file tasks.c.
Referenced by xTaskPriorityDisinherit().
Typedef Documentation
TCB_t
typedef tskTCB TCB_t
Definition at line 367 of file tasks.c.
tskTCB
typedef struct tskTaskControlBlock tskTCB
Function Documentation
eTaskGetState()
eTaskState eTaskGetState (TaskHandle_t xTask)
task. h
eTaskState eTaskGetState(TaskHandle_t xTask);
INCLUDE_eTaskGetState must be defined as 1 for this function to be available. See the configuration section for more information.
Obtain the state of any task. States are encoded by the eTaskState enumerated type.
Parameters
xTask Handle of the task to be queried.
Returns
The state of xTask at the time the function was called. Note the state of the task might change between the function being called, and the functions return value being tested by the calling task.
Definition at line 1276 of file tasks.c.
References configASSERT, eBlocked, eDeleted, eReady, eRunning, eSuspended, listLIST_ITEM_CONTAINER, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, taskENTER_CRITICAL, taskEXIT_CRITICAL, tskTaskControlBlock::xEventListItem, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTasksWaitingTermination.
Referenced by uxTaskGetSystemState(), and vTaskGetInfo().
pcTaskGetName()
char* pcTaskGetName (TaskHandle_t xTaskToQuery)
Definition at line 2188 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, listCURRENT_LIST_LENGTH, listGET_OWNER_OF_NEXT_ENTRY, mtCOVERAGE_TEST_MARKER, tskTaskControlBlock::pcTaskName, prvGetTCBFromHandle, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskIDLE_PRIORITY, vTaskSuspendAll(), xSuspendedTaskList, xTaskGetHandle(), xTaskResumeAll(), and xTasksWaitingTermination.
portTASK_FUNCTION()
static portTASK_FUNCTION (prvIdleTask , pvParameters) static
THIS IS THE RTOS IDLE TASK - WHICH IS CREATED AUTOMATICALLY WHEN THE SCHEDULER IS STARTED.
Definition at line 3138 of file tasks.c.
References configASSERT, configEXPECTED_IDLE_TIME_BEFORE_SLEEP, eAbortSleep, eNoTasksWaitingTimeout, eStandardSleep, eTaskConfirmSleepModeStatus(), listCURRENT_LIST_LENGTH, mtCOVERAGE_TEST_MARKER, pdFALSE, portSUPPRESS_TICKS_AND_SLEEP, prvCheckTasksWaitingTermination(), pxReadyTasksLists, taskYIELD, traceLOW_POWER_IDLE_BEGIN, traceLOW_POWER_IDLE_END, tskIDLE_PRIORITY, uxCurrentNumberOfTasks, vTaskSuspendAll(), xNextTaskUnblockTime, xPendingReadyList, xSuspendedTaskList, xTaskResumeAll(), xTickCount, and xYieldPending.
prvAddCurrentTaskToDelayedList()
static void prvAddCurrentTaskToDelayedList (TickType_t xTicksToWait, const BaseType_t xCanBlockIndefinitely) static
Definition at line 4699 of file tasks.c.
References listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, portMAX_DELAY, portRESET_READY_PRIORITY, pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, vListInsert(), vListInsertEnd(), xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, and xTickCount.
Referenced by ulTaskNotifyTake(), vTaskDelay(), vTaskDelayUntil(), vTaskPlaceOnEventList(), vTaskPlaceOnEventListRestricted(), vTaskPlaceOnUnorderedEventList(), and xTaskNotifyWait().
prvAddNewTaskToReadyList()
static void prvAddNewTaskToReadyList (TCB_t * pxNewTCB) static
Definition at line 970 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, portSETUP_TCB, prvAddTaskToReadyList, prvInitialiseTaskLists(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_CREATE, uxCurrentNumberOfTasks, tskTaskControlBlock::uxPriority, tskTaskControlBlock::uxTaskNumber, tskTaskControlBlock::uxTCBNumber, and xSchedulerRunning.
prvCheckTasksWaitingTermination()
static void prvCheckTasksWaitingTermination (void) static
THIS FUNCTION IS CALLED FROM THE RTOS IDLE TASK
Definition at line 3372 of file tasks.c.
References listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, prvDeleteTCB(), taskENTER_CRITICAL, taskEXIT_CRITICAL, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), vTaskSuspendAll(), tskTaskControlBlock::xStateListItem, xTaskResumeAll(), and xTasksWaitingTermination.
Referenced by portTASK_FUNCTION().
prvDeleteTCB()
static void prvDeleteTCB (TCB_t * pxTCB) static
Definition at line 3588 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, portCLEAN_UP_TCB, tskTaskControlBlock::pxStack, tskDYNAMICALLY_ALLOCATED_STACK_AND_TCB, tskSTATICALLY_ALLOCATED_STACK_AND_TCB, tskSTATICALLY_ALLOCATED_STACK_ONLY, and vPortFree().
Referenced by prvCheckTasksWaitingTermination(), and vTaskDelete().
prvInitialiseNewTask()
static void prvInitialiseNewTask (TaskFunction_t pxTaskCode, const char *const pcName, const uint32_t ulStackDepth, void *const pvParameters, UBaseType_t uxPriority, TaskHandle_t *const pxCreatedTask, TCB_t * pxNewTCB, const MemoryRegion_t *const xRegions) static
Definition at line 767 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, configNUM_THREAD_LOCAL_STORAGE_POINTERS, listSET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, tskTaskControlBlock::pcTaskName, pdFALSE, pdTRUE, portBYTE_ALIGNMENT_MASK, portPOINTER_SIZE_TYPE, portPRIVILEGE_BIT, tskTaskControlBlock::pvThreadLocalStoragePointers, pxPortInitialiseStack(), tskTaskControlBlock::pxStack, tskTaskControlBlock::pxTopOfStack, taskNOT_WAITING_NOTIFICATION, tskSTACK_FILL_BYTE, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, tskTaskControlBlock::uxBasePriority, tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, vListInitialiseItem(), tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
prvInitialiseTaskLists() [1/2]
static void prvInitialiseTaskLists (static void prvCheckTasksWaitingTermination void) static
Definition at line 456 of file tasks.c.
Referenced by prvAddNewTaskToReadyList().
prvInitialiseTaskLists() [2/2]
static void prvInitialiseTaskLists (void) static
Definition at line 3340 of file tasks.c.
References configMAX_PRIORITIES, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, tskTaskControlBlock::uxPriority, vListInitialise(), xDelayedTaskList1, xDelayedTaskList2, xPendingReadyList, xSuspendedTaskList, and xTasksWaitingTermination.
prvListTasksWithinSingleList()
static UBaseType_t prvListTasksWithinSingleList (TaskStatus_t * pxTaskStatusArray, List_t * pxList, eTaskState eState) static
Definition at line 3507 of file tasks.c.
References listCURRENT_LIST_LENGTH, listGET_OWNER_OF_NEXT_ENTRY, mtCOVERAGE_TEST_MARKER, pdTRUE, and vTaskGetInfo().
Referenced by uxTaskGetSystemState().
prvResetNextTaskUnblockTime()
static void prvResetNextTaskUnblockTime (void) static
Definition at line 3642 of file tasks.c.
References listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, pdFALSE, portMAX_DELAY, pxDelayedTaskList, xNextTaskUnblockTime, and tskTaskControlBlock::xStateListItem.
Referenced by vTaskDelete(), vTaskSuspend(), xTaskGenericNotify(), xTaskRemoveFromEventList(), and xTaskResumeAll().
prvTaskCheckFreeStackSpace()
static uint16_t prvTaskCheckFreeStackSpace (const uint8_t * pucStackByte) static
Definition at line 3540 of file tasks.c.
References portSTACK_GROWTH, prvGetTCBFromHandle, tskTaskControlBlock::pxStack, tskSTACK_FILL_BYTE, and uxTaskGetStackHighWaterMark().
Referenced by vTaskGetInfo().
prvTaskIsTaskSuspended()
static BaseType_t prvTaskIsTaskSuspended (const TaskHandle_t xTask) static
Utility task that simply returns pdTRUE if the task referenced by xTask is currently in the Suspended state, or pdFALSE if the task referenced by xTask is in any other state.
Definition at line 1663 of file tasks.c.
References configASSERT, listIS_CONTAINED_WITHIN, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xSuspendedTaskList.
Referenced by vTaskResume(), and xTaskResumeFromISR().
pvTaskGetThreadLocalStoragePointer()
void* pvTaskGetThreadLocalStoragePointer (TaskHandle_t xTaskToQuery, BaseType_t xIndex)
Definition at line 3303 of file tasks.c.
References configNUM_THREAD_LOCAL_STORAGE_POINTERS, prvGetTCBFromHandle, tskTaskControlBlock::pvThreadLocalStoragePointers, and vTaskAllocateMPURegions().
pvTaskIncrementMutexHeldCount()
void* pvTaskIncrementMutexHeldCount (void)
Definition at line 4185 of file tasks.c.
References pxCurrentTCB, and tskTaskControlBlock::uxMutexesHeld.
Referenced by xQueueGenericReceive().
ulTaskNotifyTake()
uint32_t ulTaskNotifyTake (BaseType_t xClearCountOnExit, TickType_t xTicksToWait)
Definition at line 4202 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_TAKE, traceTASK_NOTIFY_TAKE_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
uxTaskGetNumberOfTasks()
UBaseType_t uxTaskGetNumberOfTasks (void)
Definition at line 2180 of file tasks.c.
References uxCurrentNumberOfTasks.
uxTaskGetSystemState()
UBaseType_t uxTaskGetSystemState (TaskStatus_t *const pxTaskStatusArray, const UBaseType_t uxArraySize, uint32_t *const pulTotalRunTime)
configUSE_TRACE_FACILITY must be defined as 1 in FreeRTOSConfig.h for uxTaskGetSystemState() to be available.
uxTaskGetSystemState() populates an TaskStatus_t structure for each task in the system. TaskStatus_t structures contain, among other things, members for the task handle, task name, task priority, task state, and total amount of run time consumed by the task. See the TaskStatus_t structure definition in this file for the full member list.
NOTE: This function is intended for debugging use only as its use results in the scheduler remaining suspended for an extended period.
Parameters
pxTaskStatusArray A pointer to an array of TaskStatus_t structures. The array must contain at least one TaskStatus_t structure for each task that is under the control of the RTOS. The number of tasks under the control of the RTOS can be determined using the uxTaskGetNumberOfTasks() API function.
uxArraySize The size of the array pointed to by the pxTaskStatusArray parameter. The size is specified as the number of indexes in the array, or the number of TaskStatus_t structures contained in the array, not by the number of bytes in the array.
pulTotalRunTime If configGENERATE_RUN_TIME_STATS is set to 1 in FreeRTOSConfig.h then *pulTotalRunTime is set by uxTaskGetSystemState() to the total run time (as defined by the run time stats clock, see http://www.freertos.org/rtos-run-time-stats.html) since the target booted. pulTotalRunTime can be set to NULL to omit the total run time information.
Returns
The number of TaskStatus_t structures that were populated by uxTaskGetSystemState(). This should equal the number returned by the uxTaskGetNumberOfTasks() API function, but will be zero if the value passed in the uxArraySize parameter was too small.
Example usage:
 // This example demonstrates how a human readable table of run time stats
 // information is generated from raw data provided by uxTaskGetSystemState().
 // The human readable table is written to pcWriteBuffer
 void vTaskGetRunTimeStats( char *pcWriteBuffer )
 {
 TaskStatus_t *pxTaskStatusArray;
 volatile UBaseType_t uxArraySize, x;
 uint32_t ulTotalRunTime, ulStatsAsPercentage;
    // Make sure the write buffer does not contain a string.
    *pcWriteBuffer = 0x00;
    // Take a snapshot of the number of tasks in case it changes while this
    // function is executing.
    uxArraySize = uxTaskGetNumberOfTasks();
    // Allocate a TaskStatus_t structure for each task.  An array could be
    // allocated statically at compile time.
    pxTaskStatusArray = pvPortMalloc( uxArraySize * sizeof( TaskStatus_t ) );
    if( pxTaskStatusArray != NULL )
    {
        // Generate raw status information about each task.
        uxArraySize = uxTaskGetSystemState( pxTaskStatusArray, uxArraySize, &ulTotalRunTime );
        // For percentage calculations.
        ulTotalRunTime /= 100UL;
        // Avoid divide by zero errors.
        if( ulTotalRunTime > 0 )
        {
            // For each populated position in the pxTaskStatusArray array,
            // format the raw data as human readable ASCII data
            for( x = 0; x < uxArraySize; x++ )
            {
                // What percentage of the total run time has the task used?
                // This will always be rounded down to the nearest integer.
                // ulTotalRunTimeDiv100 has already been divided by 100.
                ulStatsAsPercentage = pxTaskStatusArray[ x ].ulRunTimeCounter / ulTotalRunTime;
                if( ulStatsAsPercentage > 0UL )
                {
                    sprintf( pcWriteBuffer, "%s\t\t%lu\t\t%lu%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter, ulStatsAsPercentage );
                }
                else
                {
                    // If the percentage is zero here then the task has
                    // consumed less than 1% of the total run time.
                    sprintf( pcWriteBuffer, "%s\t\t%lu\t\t<1%%\r\n", pxTaskStatusArray[ x ].pcTaskName, pxTaskStatusArray[ x ].ulRunTimeCounter );
                }
                pcWriteBuffer += strlen( ( char * ) pcWriteBuffer );
            }
        }
        // The array is no longer needed, free the memory it consumes.
        vPortFree( pxTaskStatusArray );
    }
 }
Definition at line 2328 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, eBlocked, eDeleted, eReady, eSuspended, eTaskGetState(), listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvListTasksWithinSingleList(), pxCurrentTCB, pxDelayedTaskList, pxOverflowDelayedTaskList, pxReadyTasksLists, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceINCREASE_TICK_COUNT, tskIDLE_PRIORITY, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, vTaskStepTick(), vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, xIdleTaskHandle, xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xSuspendedTaskList, xTaskAbortDelay(), xTaskGetIdleTaskHandle(), xTaskResumeAll(), xTasksWaitingTermination, xTickCount, and xYieldPending.
Referenced by xTaskPriorityDisinherit().
uxTaskGetTaskNumber()
UBaseType_t uxTaskGetTaskNumber (TaskHandle_t xTask)
Definition at line 3091 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
uxTaskPriorityGet()
UBaseType_t uxTaskPriorityGet (TaskHandle_t xTask)
Definition at line 1347 of file tasks.c.
References prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, and tskTaskControlBlock::uxPriority.
uxTaskPriorityGetFromISR()
UBaseType_t uxTaskPriorityGetFromISR (TaskHandle_t xTask)
task. h
UBaseType_t uxTaskPriorityGetFromISR(TaskHandle_t xTask);
A version of uxTaskPriorityGet() that can be used from an ISR.
Definition at line 1369 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvGetTCBFromHandle, and tskTaskControlBlock::uxPriority.
uxTaskResetEventItemValue()
TickType_t uxTaskResetEventItemValue (void)
Definition at line 4169 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listSET_LIST_ITEM_VALUE, pxCurrentTCB, tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskDelay()
void vTaskDelay (const TickType_t xTicksToDelay)
Definition at line 1231 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY, uxSchedulerSuspended, vTaskSuspendAll(), and xTaskResumeAll().
Referenced by vLEDTask1(), and vLEDTask2().
vTaskDelayUntil()
void vTaskDelayUntil (TickType_t *const pxPreviousWakeTime, const TickType_t xTimeIncrement)
Definition at line 1147 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), traceTASK_DELAY_UNTIL, uxSchedulerSuspended, vTaskSuspendAll(), xTaskResumeAll(), and xTickCount.
vTaskDelete()
void vTaskDelete (TaskHandle_t xTaskToDelete)
Definition at line 1055 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portPRE_TASK_DELETE_HOOK, portYIELD_WITHIN_API, prvDeleteTCB(), prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskRESET_READY_PRIORITY, traceTASK_DELETE, uxCurrentNumberOfTasks, uxDeletedTasksWaitingCleanUp, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::uxTaskNumber, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, xTasksWaitingTermination, and xYieldPending.
vTaskEndScheduler()
void vTaskEndScheduler (void)
Definition at line 1940 of file tasks.c.
References pdFALSE, portDISABLE_INTERRUPTS, vPortEndScheduler(), and xSchedulerRunning.
vTaskGetInfo()
void vTaskGetInfo (TaskHandle_t xTask, TaskStatus_t * pxTaskStatus, BaseType_t xGetFreeStackSpace, eTaskState eState)
Definition at line 3418 of file tasks.c.
References eBlocked, xTASK_STATUS::eCurrentState, eInvalid, eSuspended, eTaskGetState(), listLIST_ITEM_CONTAINER, xTASK_STATUS::pcTaskName, tskTaskControlBlock::pcTaskName, pdFALSE, prvGetTCBFromHandle, prvTaskCheckFreeStackSpace(), tskTaskControlBlock::pxStack, xTASK_STATUS::pxStackBase, xTASK_STATUS::ulRunTimeCounter, xTASK_STATUS::usStackHighWaterMark, xTASK_STATUS::uxBasePriority, tskTaskControlBlock::uxBasePriority, xTASK_STATUS::uxCurrentPriority, tskTaskControlBlock::uxPriority, tskTaskControlBlock::uxTCBNumber, vTaskSuspendAll(), tskTaskControlBlock::xEventListItem, xTASK_STATUS::xHandle, xTASK_STATUS::xTaskNumber, and xTaskResumeAll().
Referenced by prvListTasksWithinSingleList().
vTaskMissedYield()
void vTaskMissedYield (void)
Definition at line 3083 of file tasks.c.
References pdTRUE, and xYieldPending.
Referenced by prvUnlockQueue().
vTaskNotifyGiveFromISR()
void vTaskNotifyGiveFromISR (TaskHandle_t xTaskToNotify, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4580 of file tasks.c.
References configASSERT, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_GIVE_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
vTaskPlaceOnEventList()
void vTaskPlaceOnEventList (List_t *const pxEventList, const TickType_t xTicksToWait)
Definition at line 2827 of file tasks.c.
References configASSERT, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, vListInsert(), and tskTaskControlBlock::xEventListItem.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
vTaskPlaceOnEventListRestricted()
void vTaskPlaceOnEventListRestricted (List_t *const pxEventList, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
Definition at line 2870 of file tasks.c.
References configASSERT, pdFALSE, portMAX_DELAY, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, traceTASK_DELAY_UNTIL, vListInsertEnd(), tskTaskControlBlock::xEventListItem, and xTickCount.
Referenced by vQueueWaitForMessageRestricted().
vTaskPlaceOnUnorderedEventList()
void vTaskPlaceOnUnorderedEventList (List_t * pxEventList, const TickType_t xItemValue, const TickType_t xTicksToWait)
Definition at line 2844 of file tasks.c.
References configASSERT, listSET_LIST_ITEM_VALUE, pdTRUE, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxSchedulerSuspended, vListInsertEnd(), and tskTaskControlBlock::xEventListItem.
Referenced by xEventGroupSync(), and xEventGroupWaitBits().
vTaskPriorityInherit()
void vTaskPriorityInherit (TaskHandle_t const pxMutexHolder)
Definition at line 3713 of file tasks.c.
References configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, pxCurrentTCB, pxReadyTasksLists, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_INHERIT, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
Referenced by xQueueGenericReceive().
vTaskPrioritySet()
void vTaskPrioritySet (TaskHandle_t xTask, UBaseType_t uxNewPriority)
Definition at line 1409 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, listGET_LIST_ITEM_VALUE, listIS_CONTAINED_WITHIN, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portRESET_READY_PRIORITY, prvAddTaskToReadyList, prvGetTCBFromHandle, pxCurrentTCB, pxReadyTasksLists, taskENTER_CRITICAL, taskEVENT_LIST_ITEM_VALUE_IN_USE, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_PRIORITY_SET, tskTaskControlBlock::uxBasePriority, uxListRemove(), tskTaskControlBlock::uxPriority, uxTopReadyPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
vTaskResume()
void vTaskResume (TaskHandle_t xTaskToResume)
Definition at line 1709 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, traceTASK_RESUME, uxListRemove(), tskTaskControlBlock::uxPriority, and tskTaskControlBlock::xStateListItem.
vTaskSetTaskNumber()
void vTaskSetTaskNumber (TaskHandle_t xTask, const UBaseType_t uxHandle)
Definition at line 3114 of file tasks.c.
References tskTaskControlBlock::uxTaskNumber.
vTaskSetThreadLocalStoragePointer()
void vTaskSetThreadLocalStoragePointer (TaskHandle_t xTaskToSet, BaseType_t xIndex, void * pvValue)
Definition at line 3287 of file tasks.c.
References configNUM_THREAD_LOCAL_STORAGE_POINTERS, prvGetTCBFromHandle, and tskTaskControlBlock::pvThreadLocalStoragePointers.
vTaskSetTimeOutState()
void vTaskSetTimeOutState (TimeOut_t *const pxTimeOut)
Definition at line 3014 of file tasks.c.
References configASSERT, xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericReceive(), xQueueGenericSend(), and xTaskCheckForTimeOut().
vTaskStartScheduler()
void vTaskStartScheduler (void)
Definition at line 1833 of file tasks.c.
References configASSERT, configMINIMAL_STACK_SIZE, errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portCONFIGURE_TIMER_FOR_RUN_TIME_STATS, portDISABLE_INTERRUPTS, portMAX_DELAY, portPRIVILEGE_BIT, pxCurrentTCB, tskIDLE_PRIORITY, xIdleTaskHandle, xNextTaskUnblockTime, xPortStartScheduler(), xSchedulerRunning, xTickCount, and xTimerCreateTimerTask().
Referenced by main().
vTaskSuspend()
void vTaskSuspend (TaskHandle_t xTaskToSuspend)
Definition at line 1573 of file tasks.c.
References configASSERT, listCURRENT_LIST_LENGTH, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvGetTCBFromHandle, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskRESET_READY_PRIORITY, traceTASK_SUSPEND, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), vTaskSwitchContext(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, tskTaskControlBlock::xStateListItem, and xSuspendedTaskList.
vTaskSuspendAll()
void vTaskSuspendAll (void)
Definition at line 1951 of file tasks.c.
References listCURRENT_LIST_LENGTH, pdFALSE, pdTRUE, pxCurrentTCB, pxReadyTasksLists, tskIDLE_PRIORITY, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, uxTopReadyPriority, xNextTaskUnblockTime, and xTickCount.
Referenced by pcTaskGetName(), portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), prvProcessTimerOrBlockTask(), pvPortMalloc(), uxTaskGetSystemState(), vEventGroupDelete(), vPortFree(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericReceive(), and xQueueGenericSend().
vTaskSwitchContext()
void vTaskSwitchContext (void)
Definition at line 2768 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, pxCurrentTCB, taskCHECK_FOR_STACK_OVERFLOW, taskSELECT_HIGHEST_PRIORITY_TASK, traceTASK_SWITCHED_IN, traceTASK_SWITCHED_OUT, uxSchedulerSuspended, and xYieldPending.
Referenced by vTaskSuspend().
xTaskCheckForTimeOut()
BaseType_t xTaskCheckForTimeOut (TimeOut_t *const pxTimeOut, TickType_t *const pxTicksToWait)
Definition at line 3022 of file tasks.c.
References configASSERT, pdFALSE, pdTRUE, portMAX_DELAY, pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskSetTimeOutState(), xNumOfOverflows, xTIME_OUT::xOverflowCount, xTickCount, and xTIME_OUT::xTimeOnEntering.
Referenced by xQueueGenericReceive(), and xQueueGenericSend().
xTaskGenericNotify()
BaseType_t xTaskGenericNotify (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue)
Definition at line 4350 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdPASS, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, taskYIELD_IF_USING_PREEMPTION, traceTASK_NOTIFY, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, tskTaskControlBlock::xEventListItem, and tskTaskControlBlock::xStateListItem.
xTaskGenericNotifyFromISR()
BaseType_t xTaskGenericNotifyFromISR (TaskHandle_t xTaskToNotify, uint32_t ulValue, eNotifyAction eAction, uint32_t * pulPreviousNotificationValue, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 4456 of file tasks.c.
References configASSERT, eIncrement, eNoAction, eSetBits, eSetValueWithoutOverwrite, eSetValueWithOverwrite, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, pxCurrentTCB, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_FROM_ISR, tskTaskControlBlock::ucNotifyState, tskTaskControlBlock::ulNotifiedValue, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
xTaskGetCurrentTaskHandle()
TaskHandle_t xTaskGetCurrentTaskHandle (void)
Definition at line 3668 of file tasks.c.
References pxCurrentTCB.
Referenced by xQueueGiveMutexRecursive(), and xQueueTakeMutexRecursive().
xTaskGetSchedulerState()
BaseType_t xTaskGetSchedulerState (void)
Definition at line 3685 of file tasks.c.
References pdFALSE, taskSCHEDULER_NOT_STARTED, taskSCHEDULER_RUNNING, taskSCHEDULER_SUSPENDED, uxSchedulerSuspended, and xSchedulerRunning.
Referenced by xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericReceive(), xQueueGenericSend(), and xTimerGenericCommand().
xTaskGetTickCount()
TickType_t xTaskGetTickCount (void)
Definition at line 2134 of file tasks.c.
References portTICK_TYPE_ENTER_CRITICAL, portTICK_TYPE_EXIT_CRITICAL, and xTickCount.
Referenced by prvSampleTimeNow().
xTaskGetTickCountFromISR()
TickType_t xTaskGetTickCountFromISR (void)
Definition at line 2149 of file tasks.c.
References portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portTICK_TYPE_CLEAR_INTERRUPT_MASK_FROM_ISR, portTICK_TYPE_SET_INTERRUPT_MASK_FROM_ISR, and xTickCount.
xTaskIncrementTick()
BaseType_t xTaskIncrementTick (void)
Definition at line 2506 of file tasks.c.
References listCURRENT_LIST_LENGTH, listGET_LIST_ITEM_VALUE, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, listLIST_ITEM_CONTAINER, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdTRUE, portMAX_DELAY, prvAddTaskToReadyList, pxCurrentTCB, pxDelayedTaskList, pxReadyTasksLists, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSWITCH_DELAYED_LISTS, traceTASK_INCREMENT_TICK, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xNextTaskUnblockTime, tskTaskControlBlock::xStateListItem, xTaskCallApplicationTaskHook(), xTickCount, and xYieldPending.
Referenced by xPortSysTickHandler(), and xTaskResumeAll().
xTaskNotifyStateClear()
BaseType_t xTaskNotifyStateClear (TaskHandle_t xTask)
Definition at line 4669 of file tasks.c.
References pdFAIL, pdPASS, prvGetTCBFromHandle, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, and tskTaskControlBlock::ucNotifyState.
xTaskNotifyWait()
BaseType_t xTaskNotifyWait (uint32_t ulBitsToClearOnEntry, uint32_t ulBitsToClearOnExit, uint32_t * pulNotificationValue, TickType_t xTicksToWait)
Definition at line 4270 of file tasks.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, prvAddCurrentTaskToDelayedList(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskNOT_WAITING_NOTIFICATION, taskNOTIFICATION_RECEIVED, taskWAITING_NOTIFICATION, traceTASK_NOTIFY_WAIT, traceTASK_NOTIFY_WAIT_BLOCK, tskTaskControlBlock::ucNotifyState, and tskTaskControlBlock::ulNotifiedValue.
xTaskPriorityDisinherit()
BaseType_t xTaskPriorityDisinherit (TaskHandle_t const pxMutexHolder)
Definition at line 3779 of file tasks.c.
References configASSERT, configMAX_PRIORITIES, configMAX_TASK_NAME_LEN, eBlocked, eDeleted, eReady, eSuspended, listSET_LIST_ITEM_VALUE, mtCOVERAGE_TEST_MARKER, tskTaskControlBlock::pcTaskName, pdFALSE, pdTRUE, portASSERT_IF_IN_ISR, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, prvAddTaskToReadyList, pvPortMalloc(), pxCurrentTCB, taskRESET_READY_PRIORITY, traceTASK_PRIORITY_DISINHERIT, tskBLOCKED_CHAR, tskDELETED_CHAR, tskREADY_CHAR, tskSUSPENDED_CHAR, xTASK_STATUS::ulRunTimeCounter, tskTaskControlBlock::uxBasePriority, uxCurrentNumberOfTasks, uxListRemove(), tskTaskControlBlock::uxMutexesHeld, tskTaskControlBlock::uxPriority, uxTaskGetSystemState(), vPortFree(), vTaskGetRunTimeStats(), vTaskList(), tskTaskControlBlock::xEventListItem, xSchedulerRunning, and tskTaskControlBlock::xStateListItem.
Referenced by prvCopyDataToQueue().
xTaskRemoveFromEventList()
BaseType_t xTaskRemoveFromEventList (const List_t *const pxEventList)
Definition at line 2901 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by prvUnlockQueue(), vQueueWaitForMessageRestricted(), xQueueGenericReceive(), xQueueGenericReset(), xQueueGenericSend(), xQueueGenericSendFromISR(), xQueueGiveFromISR(), and xQueueReceiveFromISR().
xTaskRemoveFromUnorderedEventList()
BaseType_t xTaskRemoveFromUnorderedEventList (ListItem_t * pxEventListItem, const TickType_t xItemValue)
Definition at line 2969 of file tasks.c.
References configASSERT, listGET_LIST_ITEM_OWNER, listSET_LIST_ITEM_VALUE, pdFALSE, pdTRUE, prvAddTaskToReadyList, pxCurrentTCB, taskEVENT_LIST_ITEM_VALUE_IN_USE, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xStateListItem, and xYieldPending.
Referenced by vEventGroupDelete(), and xEventGroupSetBits().
xTaskResumeAll()
BaseType_t xTaskResumeAll (void)
Definition at line 2024 of file tasks.c.
References configASSERT, listGET_OWNER_OF_HEAD_ENTRY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, prvAddTaskToReadyList, prvResetNextTaskUnblockTime(), pxCurrentTCB, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskYIELD_IF_USING_PREEMPTION, uxCurrentNumberOfTasks, uxListRemove(), uxPendedTicks, tskTaskControlBlock::uxPriority, uxSchedulerSuspended, tskTaskControlBlock::xEventListItem, xPendingReadyList, tskTaskControlBlock::xStateListItem, xTaskIncrementTick(), and xYieldPending.
Referenced by pcTaskGetName(), portTASK_FUNCTION(), prvCheckTasksWaitingTermination(), prvProcessTimerOrBlockTask(), pvPortMalloc(), uxTaskGetSystemState(), vEventGroupDelete(), vPortFree(), vTaskDelay(), vTaskDelayUntil(), vTaskGetInfo(), xEventGroupSetBits(), xEventGroupSync(), xEventGroupWaitBits(), xQueueGenericReceive(), and xQueueGenericSend().
xTaskResumeFromISR()
BaseType_t xTaskResumeFromISR (TaskHandle_t xTaskToResume)
Definition at line 1763 of file tasks.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvAddTaskToReadyList, prvTaskIsTaskSuspended(), pxCurrentTCB, traceTASK_RESUME_FROM_ISR, uxListRemove(), tskTaskControlBlock::uxPriority, uxSchedulerSuspended, vListInsertEnd(), tskTaskControlBlock::xEventListItem, xPendingReadyList, and tskTaskControlBlock::xStateListItem.
Variable Documentation
pxCurrentTCB
PRIVILEGED_DATA TCB_t* volatile pxCurrentTCB = NULL
Definition at line 372 of file tasks.c.
Referenced by eTaskGetState(), prvAddCurrentTaskToDelayedList(), prvAddNewTaskToReadyList(), pvTaskIncrementMutexHeldCount(), ulTaskNotifyTake(), uxTaskGetSystemState(), uxTaskResetEventItemValue(), vTaskDelete(), vTaskNotifyGiveFromISR(), vTaskPlaceOnEventList(), vTaskPlaceOnEventListRestricted(), vTaskPlaceOnUnorderedEventList(), vTaskPriorityInherit(), vTaskPrioritySet(), vTaskResume(), vTaskStartScheduler(), vTaskSuspend(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskCheckForTimeOut(), xTaskGenericNotify(), xTaskGenericNotifyFromISR(), xTaskGetCurrentTaskHandle(), xTaskIncrementTick(), xTaskNotifyWait(), xTaskPriorityDisinherit(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
pxDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxDelayedTaskList static
Definition at line 378 of file tasks.c.
Referenced by eTaskGetState(), pcTaskGetName(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvResetNextTaskUnblockTime(), uxTaskGetSystemState(), and xTaskIncrementTick().
pxOverflowDelayedTaskList
PRIVILEGED_DATA List_t* volatile pxOverflowDelayedTaskList static
Definition at line 379 of file tasks.c.
Referenced by eTaskGetState(), pcTaskGetName(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), and uxTaskGetSystemState().
pxReadyTasksLists
PRIVILEGED_DATA List_t pxReadyTasksLists[configMAX_PRIORITIES] static
Definition at line 375 of file tasks.c.
Referenced by pcTaskGetName(), portTASK_FUNCTION(), prvInitialiseTaskLists(), uxTaskGetSystemState(), vTaskPriorityInherit(), vTaskPrioritySet(), vTaskSuspendAll(), and xTaskIncrementTick().
uxCurrentNumberOfTasks
PRIVILEGED_DATA volatile UBaseType_t uxCurrentNumberOfTasks = (UBaseType_t) 0U static
Definition at line 396 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddNewTaskToReadyList(), prvCheckTasksWaitingTermination(), uxTaskGetNumberOfTasks(), uxTaskGetSystemState(), vTaskDelete(), vTaskSuspend(), xTaskPriorityDisinherit(), and xTaskResumeAll().
uxDeletedTasksWaitingCleanUp
PRIVILEGED_DATA volatile UBaseType_t uxDeletedTasksWaitingCleanUp = (UBaseType_t) 0U static
Definition at line 385 of file tasks.c.
Referenced by prvCheckTasksWaitingTermination(), and vTaskDelete().
uxPendedTicks
PRIVILEGED_DATA volatile UBaseType_t uxPendedTicks = (UBaseType_t) 0U static
Definition at line 400 of file tasks.c.
Referenced by xTaskIncrementTick(), and xTaskResumeAll().
uxSchedulerSuspended
PRIVILEGED_DATA volatile UBaseType_t uxSchedulerSuspended = (UBaseType_t) pdFALSE static
Definition at line 415 of file tasks.c.
Referenced by vTaskDelay(), vTaskDelayUntil(), vTaskDelete(), vTaskNotifyGiveFromISR(), vTaskPlaceOnUnorderedEventList(), vTaskSuspend(), vTaskSuspendAll(), vTaskSwitchContext(), xTaskGenericNotifyFromISR(), xTaskGetSchedulerState(), xTaskIncrementTick(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
uxTaskNumber
PRIVILEGED_DATA UBaseType_t uxTaskNumber = (UBaseType_t) 0U static
Definition at line 403 of file tasks.c.
uxTopReadyPriority
PRIVILEGED_DATA volatile UBaseType_t uxTopReadyPriority = tskIDLE_PRIORITY static
Definition at line 398 of file tasks.c.
Referenced by prvAddCurrentTaskToDelayedList(), vTaskPrioritySet(), and vTaskSuspendAll().
xDelayedTaskList1
PRIVILEGED_DATA List_t xDelayedTaskList1 static
Definition at line 376 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xDelayedTaskList2
PRIVILEGED_DATA List_t xDelayedTaskList2 static
Definition at line 377 of file tasks.c.
Referenced by prvInitialiseTaskLists().
xIdleTaskHandle
PRIVILEGED_DATA TaskHandle_t xIdleTaskHandle = NULL static
Definition at line 405 of file tasks.c.
Referenced by uxTaskGetSystemState(), and vTaskStartScheduler().
xNextTaskUnblockTime
PRIVILEGED_DATA volatile TickType_t xNextTaskUnblockTime = (TickType_t) 0U static
Definition at line 404 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), prvResetNextTaskUnblockTime(), uxTaskGetSystemState(), vTaskStartScheduler(), vTaskSuspendAll(), and xTaskIncrementTick().
xNumOfOverflows
PRIVILEGED_DATA volatile BaseType_t xNumOfOverflows = (BaseType_t) 0 static
Definition at line 402 of file tasks.c.
Referenced by vTaskSetTimeOutState(), and xTaskCheckForTimeOut().
xPendingReadyList
PRIVILEGED_DATA List_t xPendingReadyList static
Definition at line 380 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvInitialiseTaskLists(), prvTaskIsTaskSuspended(), vTaskNotifyGiveFromISR(), xTaskGenericNotifyFromISR(), xTaskRemoveFromEventList(), xTaskResumeAll(), and xTaskResumeFromISR().
xSchedulerRunning
PRIVILEGED_DATA volatile BaseType_t xSchedulerRunning = pdFALSE static
Definition at line 399 of file tasks.c.
Referenced by prvAddNewTaskToReadyList(), vTaskDelete(), vTaskEndScheduler(), vTaskStartScheduler(), vTaskSuspend(), xTaskGetSchedulerState(), and xTaskPriorityDisinherit().
xSuspendedTaskList
PRIVILEGED_DATA List_t xSuspendedTaskList static
Definition at line 391 of file tasks.c.
Referenced by eTaskGetState(), pcTaskGetName(), portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), prvInitialiseTaskLists(), prvTaskIsTaskSuspended(), uxTaskGetSystemState(), and vTaskSuspend().
xTasksWaitingTermination
PRIVILEGED_DATA List_t xTasksWaitingTermination static
Definition at line 384 of file tasks.c.
Referenced by eTaskGetState(), pcTaskGetName(), prvCheckTasksWaitingTermination(), prvInitialiseTaskLists(), uxTaskGetSystemState(), and vTaskDelete().
xTickCount
PRIVILEGED_DATA volatile TickType_t xTickCount = (TickType_t) 0U static
Definition at line 397 of file tasks.c.
Referenced by portTASK_FUNCTION(), prvAddCurrentTaskToDelayedList(), uxTaskGetSystemState(), vTaskDelayUntil(), vTaskPlaceOnEventListRestricted(), vTaskSetTimeOutState(), vTaskStartScheduler(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetTickCount(), xTaskGetTickCountFromISR(), and xTaskIncrementTick().
xYieldPending
PRIVILEGED_DATA volatile BaseType_t xYieldPending = pdFALSE static
Definition at line 401 of file tasks.c.
Referenced by portTASK_FUNCTION(), uxTaskGetSystemState(), vTaskDelete(), vTaskMissedYield(), vTaskNotifyGiveFromISR(), vTaskSwitchContext(), xTaskGenericNotifyFromISR(), xTaskIncrementTick(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), and xTaskResumeAll().